// Checklists de documentos por linha de crédito e tipo de pessoa.
// Extraído de nova-proposta-modal.tsx para ser importável em rotas server-side
// (route handlers) sem trazer dependências de UI/React junto.

export const CHECKLISTS: Record<string, Record<"PF" | "PJ", { id: string; label: string; required: boolean; hint?: string }[]>> = {
  "Home Equity": {
    PF: [
      { id: "he_pf_1", label: "RG e CPF (ou CNH)", required: true, hint: "Documento de identificação com foto" },
      { id: "he_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true, hint: "Holerite, pró-labore ou decore" },
      { id: "he_pf_3", label: "Extrato bancário (3 últimos meses)", required: true },
      { id: "he_pf_4", label: "Matrícula do imóvel atualizada (máx. 30 dias)", required: true },
      { id: "he_pf_5", label: "IPTU do ano corrente", required: true },
      { id: "he_pf_6", label: "Imposto de Renda completo + recibo de entrega", required: true },
      { id: "he_pf_7", label: "Comprovante de residência (máx. 90 dias)", required: true },
      { id: "he_pf_8", label: "Certidão de casamento / divórcio", required: false, hint: "Se aplicável" },
      { id: "he_pf_9", label: "Certidão negativa de débitos cartoriais", required: false },
      { id: "he_pf_10", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "he_pf_11", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
    PJ: [
      { id: "he_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "he_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "he_pj_3", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "he_pj_4", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "he_pj_5", label: "Certidão Negativa Federal, Estadual e Municipal", required: true },
      { id: "he_pj_6", label: "Matrícula do imóvel atualizada (máx. 30 dias)", required: true },
      { id: "he_pj_7", label: "IPTU do ano corrente", required: true },
      { id: "he_pj_8", label: "RG e CPF dos sócios e respectivos cônjuges", required: true },
      { id: "he_pj_9", label: "Imposto de Renda PJ (DIPJ) + recibo", required: true },
      { id: "he_pj_10", label: "Comprovante de residência dos sócios", required: true },
      { id: "he_pj_11", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "he_pj_12", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
  },
  "Home Equity Distressed": {
    PF: [
      { id: "hee_pf_1", label: "RG e CPF (ou CNH)", required: true, hint: "Documento de identificação com foto" },
      { id: "hee_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true, hint: "Holerite, pró-labore ou decore" },
      { id: "hee_pf_3", label: "Extrato bancário (3 últimos meses)", required: true },
      { id: "hee_pf_4", label: "Matrícula do imóvel atualizada (máx. 30 dias)", required: true, hint: "Imóvel em situação estressada / alienação" },
      { id: "hee_pf_5", label: "IPTU do ano corrente", required: true },
      { id: "hee_pf_6", label: "Imposto de Renda completo + recibo de entrega", required: true },
      { id: "hee_pf_7", label: "Comprovante de residência (máx. 90 dias)", required: true },
      { id: "hee_pf_8", label: "Certidão de ônus reais atualizada", required: true, hint: "Fundamental para imóveis estressados" },
      { id: "hee_pf_9", label: "Documentação do processo / dívida em aberto", required: true, hint: "Ação judicial, protesto ou execução" },
      { id: "hee_pf_10", label: "Laudo de avaliação do imóvel", required: false, hint: "Avaliação independente" },
      { id: "hee_pf_11", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "hee_pf_12", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
    PJ: [
      { id: "hee_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "hee_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "hee_pj_3", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "hee_pj_4", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "hee_pj_5", label: "Certidão Negativa Federal, Estadual e Municipal", required: true },
      { id: "hee_pj_6", label: "Matrícula do imóvel atualizada (máx. 30 dias)", required: true },
      { id: "hee_pj_7", label: "IPTU do ano corrente", required: true },
      { id: "hee_pj_8", label: "RG e CPF dos sócios e respectivos cônjuges", required: true },
      { id: "hee_pj_9", label: "Certidão de ônus reais atualizada", required: true, hint: "Fundamental para imóveis estressados" },
      { id: "hee_pj_10", label: "Documentação do processo / dívida em aberto", required: true, hint: "Ação judicial, protesto ou execução" },
      { id: "hee_pj_11", label: "Laudo de avaliação do imóvel", required: false },
      { id: "hee_pj_12", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "hee_pj_13", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
  },
  "Crédito no Aval": {
    PF: [
      { id: "av_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "av_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
      { id: "av_pf_3", label: "Extrato bancário (3 últimos meses)", required: true },
      { id: "av_pf_4", label: "Comprovante de residência (máx. 90 dias)", required: true },
      { id: "av_pf_5", label: "Imposto de Renda completo + recibo", required: true },
      { id: "av_pf_6", label: "Certidão de casamento / divórcio", required: false },
    ],
    PJ: [
      { id: "av_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "av_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "av_pj_3", label: "Balanço Patrimonial + DRE", required: true },
      { id: "av_pj_4", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "av_pj_5", label: "Certidões Negativas (Federal, Estadual, Municipal)", required: true },
      { id: "av_pj_6", label: "RG e CPF dos sócios", required: true },
    ],
  },
  "FIDC": {
    PF: [
      { id: "fidc_pf_1", label: "RG e CPF dos sócios/gestores", required: true },
      { id: "fidc_pf_2", label: "Comprovante de renda e patrimônio", required: true },
      { id: "fidc_pf_3", label: "Imposto de Renda + recibo", required: true },
    ],
    PJ: [
      { id: "fidc_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "fidc_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "fidc_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "fidc_pj_4", label: "Carteira de recebíveis — relatório detalhado", required: true },
      { id: "fidc_pj_5", label: "Contratos de originação de crédito (amostra)", required: true },
      { id: "fidc_pj_6", label: "Inadimplência histórica por safra", required: true },
      { id: "fidc_pj_7", label: "Certidões Negativas completas", required: true },
      { id: "fidc_pj_8", label: "Relatório de auditoria independente", required: false },
    ],
  },
  "CRI Cash Collateral": {
    PF: [
      { id: "cri_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "cri_pf_2", label: "Comprovante de renda e patrimônio", required: true },
      { id: "cri_pf_3", label: "Matrícula do imóvel vinculado", required: true },
      { id: "cri_pf_4", label: "IPTU do ano corrente", required: true },
      { id: "cri_pf_5", label: "Imposto de Renda + recibo", required: true },
      { id: "cri_pf_6", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "cri_pf_7", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
    PJ: [
      { id: "cri_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "cri_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "cri_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "cri_pj_4", label: "Matrícula do imóvel vinculado (atualizada)", required: true },
      { id: "cri_pj_5", label: "Laudo de avaliação imobiliária (CRECI)", required: true },
      { id: "cri_pj_6", label: "Memorial descritivo do empreendimento", required: true },
      { id: "cri_pj_7", label: "Certidões Negativas completas", required: true },
      { id: "cri_pj_8", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "cri_pj_9", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
  },
  "CRA": {
    PF: [
      { id: "cra_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "cra_pf_2", label: "Comprovante de atividade rural / agroindustrial", required: true },
      { id: "cra_pf_3", label: "Imposto de Renda + recibo", required: true },
      { id: "cra_pf_4", label: "CAR — Cadastro Ambiental Rural", required: true },
    ],
    PJ: [
      { id: "cra_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "cra_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "cra_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "cra_pj_4", label: "Comprovante de atividade agronegócio (contratos)", required: true },
      { id: "cra_pj_5", label: "CAR — Cadastro Ambiental Rural", required: true },
      { id: "cra_pj_6", label: "Certidões Negativas completas", required: true },
    ],
  },
  "HIGH TICKET": {
    PF: [
      { id: "ht_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "ht_pf_2", label: "Comprovante de patrimônio e renda", required: true },
      { id: "ht_pf_3", label: "Imposto de Renda (últimos 3 anos)", required: true },
      { id: "ht_pf_4", label: "Teaser executivo da operação", required: true },
      { id: "ht_pf_5", label: "Projeções financeiras (5 anos)", required: true },
    ],
    PJ: [
      { id: "ht_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "ht_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "ht_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "ht_pj_4", label: "Fluxo de Caixa histórico e projetado", required: true },
      { id: "ht_pj_5", label: "Teaser executivo / Information Memorandum", required: true },
      { id: "ht_pj_6", label: "Projeções financeiras detalhadas (5 anos)", required: true },
      { id: "ht_pj_7", label: "Certidões Negativas completas (PGFN, Receita, FGTS)", required: true },
      { id: "ht_pj_8", label: "Relatório de auditoria independente", required: true },
      { id: "ht_pj_9", label: "Laudo de avaliação patrimonial", required: false },
      { id: "ht_pj_10", label: "Apresentação executiva (pitch deck)", required: false },
    ],
  },
  "PROJECT FINANCE": {
    PF: [],
    PJ: [
      { id: "pf_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "pf_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "pf_pj_3", label: "Estudo de viabilidade do projeto", required: true },
      { id: "pf_pj_4", label: "Projeções financeiras completas (10 anos)", required: true },
      { id: "pf_pj_5", label: "Licenças ambientais e regulatórias", required: true },
      { id: "pf_pj_6", label: "Contratos off-take ou receita garantida", required: false },
      { id: "pf_pj_7", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "pf_pj_8", label: "Certidões Negativas completas", required: true },
    ],
  },
  "Fundo Construção — Moradia": {
    PF: [
      { id: "fcr_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "fcr_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
      { id: "fcr_pf_3", label: "Matrícula do terreno atualizada (máx. 30 dias)", required: true },
      { id: "fcr_pf_4", label: "IPTU do terreno — ano corrente", required: true },
      { id: "fcr_pf_5", label: "Projeto arquitetônico aprovado pela prefeitura", required: true },
      { id: "fcr_pf_6", label: "Alvará de construção", required: true },
      { id: "fcr_pf_7", label: "Orçamento da obra detalhado", required: true },
      { id: "fcr_pf_8", label: "Imposto de Renda completo + recibo", required: true },
      { id: "fcr_pf_9", label: "Certidão de casamento / divórcio", required: false },
      { id: "fcr_pf_10", label: "3 fotos internas do imóvel / obra", required: true, hint: "Estado atual da construção ou ambientes internos" },
      { id: "fcr_pf_11", label: "3 fotos externas do imóvel / obra", required: true, hint: "Fachada, terreno e área externa" },
    ],
    PJ: [
      { id: "fcr_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "fcr_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "fcr_pj_3", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "fcr_pj_4", label: "Matrícula do terreno atualizada", required: true },
      { id: "fcr_pj_5", label: "Projeto arquitetônico aprovado", required: true },
      { id: "fcr_pj_6", label: "Alvará de construção", required: true },
      { id: "fcr_pj_7", label: "Orçamento da obra detalhado + cronograma físico-financeiro", required: true },
      { id: "fcr_pj_8", label: "Memorial descritivo da construção", required: true },
      { id: "fcr_pj_9", label: "Certidões Negativas completas", required: true },
      { id: "fcr_pj_10", label: "RG e CPF dos sócios", required: true },
      { id: "fcr_pj_11", label: "3 fotos internas do imóvel / obra", required: true, hint: "Estado atual da construção ou ambientes internos" },
      { id: "fcr_pj_12", label: "3 fotos externas do imóvel / obra", required: true, hint: "Fachada, terreno e área externa" },
    ],
  },
  "HomeCash": {
    PF: [
      { id: "hc_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "hc_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
      { id: "hc_pf_3", label: "Extrato bancário (3 últimos meses)", required: true },
      { id: "hc_pf_4", label: "Matrícula do imóvel atualizada (máx. 30 dias)", required: true },
      { id: "hc_pf_5", label: "IPTU do ano corrente", required: true },
      { id: "hc_pf_6", label: "Laudo de avaliação do imóvel (CRECI)", required: true },
      { id: "hc_pf_7", label: "Imposto de Renda completo + recibo", required: true },
      { id: "hc_pf_8", label: "Comprovante de residência (máx. 90 dias)", required: true },
      { id: "hc_pf_9", label: "Certidão de casamento / divórcio", required: false },
      { id: "hc_pf_10", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "hc_pf_11", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
    PJ: [
      { id: "hc_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "hc_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "hc_pj_3", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "hc_pj_4", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "hc_pj_5", label: "Matrícula do imóvel atualizada", required: true },
      { id: "hc_pj_6", label: "Laudo de avaliação do imóvel (CRECI)", required: true },
      { id: "hc_pj_7", label: "IPTU do ano corrente", required: true },
      { id: "hc_pj_8", label: "Certidões Negativas completas", required: true },
      { id: "hc_pj_9", label: "RG e CPF dos sócios e cônjuges", required: true },
      { id: "hc_pj_10", label: "3 fotos internas do imóvel", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "hc_pj_11", label: "3 fotos externas do imóvel", required: true, hint: "Fachada, lateral e área externa" },
    ],
  },
  "Giro Auto": {
    PF: [
      { id: "v3g_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "v3g_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
      { id: "v3g_pf_3", label: "Extrato bancário (6 últimos meses)", required: true },
      { id: "v3g_pf_4", label: "Imposto de Renda completo + recibo", required: true },
    ],
    PJ: [
      { id: "v3g_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "v3g_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "v3g_pj_3", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "v3g_pj_4", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "v3g_pj_5", label: "Extrato bancário PJ (6 últimos meses)", required: true },
      { id: "v3g_pj_6", label: "Certidões Negativas (Federal, Estadual, Municipal)", required: true },
      { id: "v3g_pj_7", label: "RG e CPF dos sócios", required: true },
      { id: "v3g_pj_8", label: "Nota fiscal de faturamento (amostra 3 meses)", required: false },
    ],
  },
  "CGI — Grandes Empresas": {
    PF: [
      { id: "cgi_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "cgi_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
      { id: "cgi_pf_3", label: "Matrícula do imóvel em garantia (máx. 30 dias)", required: true },
      { id: "cgi_pf_4", label: "IPTU do ano corrente", required: true },
      { id: "cgi_pf_5", label: "Laudo de avaliação do imóvel (CRECI)", required: true },
      { id: "cgi_pf_6", label: "Imposto de Renda completo + recibo", required: true },
      { id: "cgi_pf_7", label: "Extrato bancário (6 últimos meses)", required: true },
      { id: "cgi_pf_8", label: "3 fotos internas do imóvel em garantia", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "cgi_pf_9", label: "3 fotos externas do imóvel em garantia", required: true, hint: "Fachada, lateral e área externa" },
    ],
    PJ: [
      { id: "cgi_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "cgi_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "cgi_pj_3", label: "Balanço Patrimonial + DRE (últimos 2 anos)", required: true },
      { id: "cgi_pj_4", label: "Matrícula do imóvel em garantia", required: true },
      { id: "cgi_pj_5", label: "Laudo de avaliação do imóvel (CRECI)", required: true },
      { id: "cgi_pj_6", label: "IPTU do ano corrente", required: true },
      { id: "cgi_pj_7", label: "Faturamento mensal — últimos 12 meses", required: true },
      { id: "cgi_pj_8", label: "Certidões Negativas completas", required: true },
      { id: "cgi_pj_9", label: "RG e CPF dos sócios", required: true },
      { id: "cgi_pj_10", label: "3 fotos internas do imóvel em garantia", required: true, hint: "Ambientes principais: sala, quartos, cozinha" },
      { id: "cgi_pj_11", label: "3 fotos externas do imóvel em garantia", required: true, hint: "Fachada, lateral e área externa" },
    ],
  },
  "CPR Agro": {
    PF: [
      { id: "cpr_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "cpr_pf_2", label: "CAR — Cadastro Ambiental Rural", required: true },
      { id: "cpr_pf_3", label: "ITR — Imposto Territorial Rural", required: true },
      { id: "cpr_pf_4", label: "Comprovante de atividade rural", required: true },
      { id: "cpr_pf_5", label: "Imposto de Renda completo + recibo", required: true },
      { id: "cpr_pf_6", label: "Matrícula da propriedade rural (máx. 30 dias)", required: true },
    ],
    PJ: [
      { id: "cpr_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "cpr_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "cpr_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "cpr_pj_4", label: "CAR — Cadastro Ambiental Rural", required: true },
      { id: "cpr_pj_5", label: "ITR — Imposto Territorial Rural", required: true },
      { id: "cpr_pj_6", label: "Matrícula da propriedade rural", required: true },
      { id: "cpr_pj_7", label: "Contratos de comercialização (safra futura)", required: false },
      { id: "cpr_pj_8", label: "Certidões Negativas completas", required: true },
    ],
  },
  "Op. Internacional — Cash Collateral": {
    PF: [
      { id: "ficc_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "ficc_pf_2", label: "Comprovante de patrimônio internacional", required: true },
      { id: "ficc_pf_3", label: "Extrato de conta no exterior (6 meses)", required: true },
      { id: "ficc_pf_4", label: "Declaração BACEN (se aplicável)", required: true },
      { id: "ficc_pf_5", label: "Imposto de Renda + recibo", required: true },
    ],
    PJ: [
      { id: "ficc_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "ficc_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "ficc_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "ficc_pj_4", label: "Extrato de contas no exterior", required: true },
      { id: "ficc_pj_5", label: "Comprovante de capital no exterior (colateral)", required: true },
      { id: "ficc_pj_6", label: "Declaração BACEN Capital Estrangeiro", required: true },
      { id: "ficc_pj_7", label: "Certidões Negativas completas", required: true },
      { id: "ficc_pj_8", label: "Relatório de compliance AML/KYC", required: true },
    ],
  },
  "Op. Internacional — Garantia Imobiliária": {
    PF: [
      { id: "fii_pf_1", label: "RG e CPF (ou CNH)", required: true },
      { id: "fii_pf_2", label: "Imposto de Renda + recibo", required: true },
      { id: "fii_pf_3", label: "Comprovante de patrimônio e renda", required: true },
      { id: "fii_pf_4", label: "Documentação do imóvel internacional (se aplicável)", required: false },
    ],
    PJ: [
      { id: "fii_pj_1", label: "Contrato Social + alterações", required: true },
      { id: "fii_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "fii_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "fii_pj_4", label: "Teaser do projeto imobiliário internacional", required: true },
      { id: "fii_pj_5", label: "Declaração BACEN Capital Estrangeiro", required: true },
      { id: "fii_pj_6", label: "Relatório de compliance AML/KYC", required: true },
      { id: "fii_pj_7", label: "Certidões Negativas completas", required: true },
    ],
  },
  "Crédito Ponto / CRI Início de Obra": {
    PF: [],
    PJ: [
      { id: "fcl_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "fcl_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "fcl_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "fcl_pj_4", label: "Matrícula da área bruta do loteamento", required: true },
      { id: "fcl_pj_5", label: "Projeto de loteamento aprovado — SEURB/Prefeitura", required: true },
      { id: "fcl_pj_6", label: "Licença Ambiental (LP + LI + LO)", required: true },
      { id: "fcl_pj_7", label: "Orçamento de obras de infraestrutura", required: true },
      { id: "fcl_pj_8", label: "Cronograma físico-financeiro do loteamento", required: true },
      { id: "fcl_pj_9", label: "Estudo de viabilidade econômica (VGV e custos)", required: true },
      { id: "fcl_pj_10", label: "Certidões Negativas completas", required: true },
      { id: "fcl_pj_11", label: "RG e CPF dos sócios", required: true },
    ],
  },
  "Construtoras BTS — Build-to-Suit": {
    PF: [],
    PJ: [
      { id: "fce_pj_1", label: "Contrato Social + todas as alterações", required: true },
      { id: "fce_pj_2", label: "Cartão CNPJ atualizado", required: true },
      { id: "fce_pj_3", label: "Balanço Patrimonial + DRE (últimos 3 anos)", required: true },
      { id: "fce_pj_4", label: "Matrícula do terreno atualizada (máx. 30 dias)", required: true },
      { id: "fce_pj_5", label: "Projeto arquitetônico aprovado + HABITE-SE parcial (se retrofit)", required: true },
      { id: "fce_pj_6", label: "Licença Ambiental e Alvará de Construção", required: true },
      { id: "fce_pj_7", label: "Memorial descritivo do empreendimento", required: true },
      { id: "fce_pj_8", label: "Orçamento de obras + cronograma físico-financeiro", required: true },
      { id: "fce_pj_9", label: "Estudo de viabilidade (VGV, custo e margem)", required: true },
      { id: "fce_pj_10", label: "Contrato de venda de unidades (se houver)", required: false },
      { id: "fce_pj_11", label: "Certidões Negativas completas (PGFN, Receita, FGTS)", required: true },
      { id: "fce_pj_12", label: "RG e CPF dos sócios e cônjuges", required: true },
    ],
  },
};

export const DEFAULT_CHECKLIST = {
  PF: [
    { id: "def_pf_1", label: "RG e CPF (ou CNH)", required: true },
    { id: "def_pf_2", label: "Comprovante de renda (3 últimos meses)", required: true },
    { id: "def_pf_3", label: "Comprovante de residência (máx. 90 dias)", required: true },
    { id: "def_pf_4", label: "Imposto de Renda completo + recibo", required: true },
  ],
  PJ: [
    { id: "def_pj_1", label: "Contrato Social + alterações", required: true },
    { id: "def_pj_2", label: "Cartão CNPJ atualizado", required: true },
    { id: "def_pj_3", label: "Balanço Patrimonial + DRE", required: true },
    { id: "def_pj_4", label: "Certidões Negativas", required: true },
  ],
};

// ─── Linhas por nível ──────────────────────────────────────────────────────
export const LEVEL_LINES: Record<string, string[]> = {
  NIVEL_1: [
    "V3Equity",
    "Home Equity",
    "Home Equity Distressed",
    "Giro Auto",
    "V3Auto",
    "Crédito no Aval",
    "Financiamento Imobiliário",
    "Capital Maquinários",
  ],
  NIVEL_2: [
    "HomeCash",
    "CGI — Grandes Empresas",
    "Cash Collateral",
    "Fundo Construção — Moradia",
    "Fundo Construção — Reforma",
    "Fundo Construção — Unifamiliar",
    "Fundo Construção — Geminados",
    "Financiamento — Brasileiros no Exterior",
    "CPR Agro",
    "Câmbio Pronto",
    "FINIMP — Financiamento de Importações",
    "ACC — Adiantamento s/ Contrato de Câmbio",
    "ACE — Adiantamento s/ Cambiais Entregues",
  ],
  NIVEL_3: [
    "Sale Leaseback Agro",
    "Op. Internacional — Cash Collateral",
    "CRI Cash Collateral",
    "Crédito Ponto / CRI Início de Obra",
    "Construtoras BTS — Build-to-Suit",
    "Fundo Incorporadoras",
    "Op. Internacional — Garantia Imobiliária",
  ],
};
