import { NextRequest, NextResponse } from "next/server";
import { createClient as sc } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/server";

function svc() {
  return sc(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
}

const ADMIN_ROLES = ["ADMIN", "GESTAO", "MESA_OPERACIONAL"];

async function getUser() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { user: null, profile: null };
  const { data: profile } = await supabase.from("profiles").select("id, role").eq("id", user.id).single();
  return { user, profile };
}

// Valores padrão — Portfólio V3 Partners 2026 (completo)
const DEFAULT_REGRAS = [
  // ── NÍVEL 1 — Varejo ───────────────────────────────────────────────────────
  { id: "v3equity",           nome: "V3Equity",                                    nivel: "NIVEL_1", categoria: "Crédito com Garantia Imobiliária",                    cor: "#3B82F6", emoji: "🏠", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: false, valor_minimo: 300000,   valor_maximo: 10000000,  ltv_maximo: 0.60, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 55, keywords_finalidade: ["imovel","casa","residencial","quitacao","v3equity"],                              descricao: "Linha autoral V3. Sem consulta ao BACEN. Sem endividamento adicional. Taxa a partir de 0,45% a.m. + INPC. Prazo até 220 meses. LTV 30–60%. Retorno de 3–5% do Fundo de Reserva.",          observacoes_internas: "Aceita restrições — sem consulta ao BACEN. Diferencial: sem endividamento adicional." },
  { id: "home_equity",        nome: "Home Equity",                                 nivel: "NIVEL_1", categoria: "Crédito com Garantia Imobiliária",                    cor: "#60A5FA", emoji: "🏡", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: true,  valor_minimo: 80000,    valor_maximo: 10000000,  ltv_maximo: 0.50, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 60, keywords_finalidade: ["imovel","casa","residencial","imóvel","equity"],                                   descricao: "Elegibilidade ágil. Aceita empresas em recuperação judicial. CET 0,7–0,9% a.m. + IPCA. Prazo 60–240 meses. LTV 30–50%. Aporte R$80K–R$10M. Estruturação aprox. 30 dias.",                  observacoes_internas: "Aceita recuperação judicial. Amortização SAC ou Price." },
  { id: "distressed",         nome: "Home Equity Distressed",                      nivel: "NIVEL_1", categoria: "Crédito com Garantia Imobiliária — Restrições",       cor: "#F97316", emoji: "🔓", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: false, valor_minimo: 80000,    valor_maximo: 10000000,  ltv_maximo: 0.50, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["restricao","negativado","distressed","divida"],                                    descricao: "Para clientes com restrições. Não analisa capacidade de pagamento. Taxa 2,99% a.m. LTV 30–50%. Prazo 24–48 meses + 24 de prorrogação. Análise personalizada.",                              observacoes_internas: "Produto específico para restrição/negativação. Taxa elevada — validar saída." },
  { id: "giro_auto",          nome: "Giro Auto",                                   nivel: "NIVEL_1", categoria: "Crédito com Garantia Veicular",                       cor: "#06B6D4", emoji: "🚛", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 200000,   valor_maximo: 10000000,  ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["frota","veiculo","caminhão","caminhao","carreta","truck"],                         descricao: "Capital de giro com frota como garantia. Sem consulta ao BACEN. CET 1,0–1,45% a.m. + IPCA. Prazo 40–80 meses. R$200K–R$10M. Retorno 3–5% Fundo de Reserva.",                               observacoes_internas: "Garante: leves até 9 anos, pesados até 7 anos. Sem endividamento adicional." },
  { id: "v3auto",             nome: "V3Auto",                                       nivel: "NIVEL_1", categoria: "Crédito com Garantia Veicular — Pesados",             cor: "#0891B2", emoji: "🚚", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 50000,    valor_maximo: 5000000,   ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 25, keywords_finalidade: ["pesado","scania","volvo","iveco","mercedes","carreta","caminhão"],                  descricao: "100% digital. Scania, Iveco, Volvo, VW, Mercedes, Fachini. Taxa a partir de 1,7% a.m. Prazo até 60 meses. R$50K–R$5M. Sem TAC.",                                                           observacoes_internas: "Pesados 0km com 10% de entrada. Taxa média 1,39% a.m." },
  { id: "credito_aval",       nome: "Crédito no Aval",                             nivel: "NIVEL_1", categoria: "Crédito Empresarial sem Garantia Real",               cor: "#8B5CF6", emoji: "🤝", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 10000,    valor_maximo: 500000,    ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 20000,   score_base: 35, keywords_finalidade: ["aval","rating","sem garantia","capital","operacional"],                            descricao: "Sem garantia real. Aprovação por rating e histórico financeiro. Taxa 2–3,5% a.m. Prazo 6–60 meses. Até R$500K. 100% digital. Fat. R$240K–R$12M/ano.",                                      observacoes_internas: "Aprovação rápida. R$1M especial disponível. 100% digital." },
  { id: "fin_imobiliario",    nome: "Financiamento Imobiliário",                   nivel: "NIVEL_1", categoria: "Financiamento para Aquisição de Imóvel",              cor: "#10B981", emoji: "🏘️", tipo_pessoa: "PF",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 300000,   valor_maximo: null,      ltv_maximo: 0.60, min_renda_mensal: 4000,   min_faturamento_mensal: 0,       score_base: 40, keywords_finalidade: ["compra","aquisição","aquisicao","casa","apartamento","apart","imovel"],            descricao: "Residencial e comercial. ITBI e cartório incluídos. Taxa a partir de 1,50% a.m. + IPCA. LTV até 60%. Prazo 168–240 meses. Renda mínima R$4K/mês.",                                          observacoes_internas: "ITBI e cartório incluídos. Melhores condições acima de R$5M." },
  { id: "capital_maquinarios",nome: "Capital Maquinários",                         nivel: "NIVEL_1", categoria: "Crédito com Garantia de Maquinário — Agro",           cor: "#D97706", emoji: "🚜", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 25000,    valor_maximo: 10000000,  ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 20, keywords_finalidade: ["maquina","trator","colheitadeira","implemento","linha amarela","agro"],             descricao: "Refinanciamento de máquinas usadas. Linha amarela, carretas e caminhões. Taxa 1,1% a.m. + IPCA. Prazo até 60 meses + 1 ano carência. R$25K–R$10M.",                                         observacoes_internas: "Pesados 0km com 10% de entrada. Condiçōes especiais para transporte." },
  // ── NÍVEL 2 — Estruturado ─────────────────────────────────────────────────
  { id: "homecash",           nome: "HomeCash",                                     nivel: "NIVEL_2", categoria: "Crédito com Garantia Imobiliária — Fundo Compra",     cor: "#F59E0B", emoji: "💰", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: false, valor_minimo: 400000,   valor_maximo: 7000000000,ltv_maximo: 0.60, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 40, keywords_finalidade: ["liquidez","capital","giro","fundo compra","homecash"],                             descricao: "Fundo compra o imóvel. Contratos de compra, posse e recompra garantida. Taxa 0,5% a.m. Prazo 18 meses. LTV até 60%. Custo final 20–30% do captado. Liquidez imediata.",                     observacoes_internas: "Ideal para empresas e produtores rurais com necessidade de liquidez imediata." },
  { id: "cgi_pj",             nome: "CGI — Grandes Empresas",                      nivel: "NIVEL_2", categoria: "Crédito com Garantia Imobiliária — PJ Grande Porte",  cor: "#10B981", emoji: "🏢", tipo_pessoa: "PJ",    requer_imovel: true,  bloqueia_restricao: true,  valor_minimo: 200000,   valor_maximo: 10000000,  ltv_maximo: 0.60, min_renda_mensal: 0,      min_faturamento_mensal: 2500000, score_base: 40, keywords_finalidade: ["imobiliario","comercial","industrial","galpao","cgi"],                             descricao: "Empresas de maior porte. Faturamento a partir de R$30M/ano. Utilização gradual em até 5 anos. Taxa a partir de 1,15% a.m. + IPCA. Prazo 60–240 meses.",                                     observacoes_internas: "Aceita Interveniente Quitante. Análise jurídica para inventário e situações documentais complexas." },
  { id: "cash_collateral",    nome: "Cash Collateral",                             nivel: "NIVEL_2", categoria: "Crédito Empresarial com Garantia Líquida",             cor: "#6366F1", emoji: "💎", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 100000,   valor_maximo: 10000000,  ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 35, keywords_finalidade: ["cdb","titulo","garantia liquida","aplicação","aplicacao","colateral"],             descricao: "Garantias líquidas (CDB, títulos bloqueados) como alavanca. Taxa a partir de 12% a.a. + CDI. Até R$10M. Estruturação 15–60 dias.",                                                          observacoes_internas: "Juros menores pelo menor risco. Alavancagem proporcional ao colateral." },
  { id: "moradia",            nome: "Fundo Construção — Moradia",                  nivel: "NIVEL_2", categoria: "Fundo Construção Residencial",                         cor: "#84CC16", emoji: "🏗️", tipo_pessoa: "PF",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 300000,   valor_maximo: null,      ltv_maximo: 0.99, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["construção","construcao","obra","moradia","terreno","projeto aprovado"],           descricao: "PF. Projeto aprovado + licença ambiental. Taxa a partir de 9% a.a. + CDI. LTV 80–99% da obra. Aporte mínimo R$300K. Portabilidade pós-conclusão.",                                         observacoes_internas: "Exige projeto aprovado e licença ambiental. Portabilidade pós-obra." },
  { id: "reforma",            nome: "Fundo Construção — Reforma",                  nivel: "NIVEL_2", categoria: "Fundo Construção — Reforma e Ampliação",              cor: "#A78BFA", emoji: "🔨", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: true,  valor_minimo: 30000,    valor_maximo: 10000000,  ltv_maximo: 0.50, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["reforma","renovação","renovacao","ampliação","ampliacao","melhoria"],               descricao: "Avaliação em até 48h. Liberação em tranches na conta. Taxa a partir de 1,15% a.m. + IPCA. LTV até 50% do imóvel. R$30K–R$10M.",                                                             observacoes_internas: "Com ou sem financiamento pré-existente. Flexível na documentação." },
  { id: "unifamiliar",        nome: "Fundo Construção — Unifamiliar",              nivel: "NIVEL_2", categoria: "Fundo Construção — Pequenos Construtores",             cor: "#EC4899", emoji: "🏠", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 300000,   valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 20, keywords_finalidade: ["unifamiliar","construtor","construção residencial","pequeno construtor"],           descricao: "Pequenos e médios construtores. Tranches conforme avanço físico. Taxa IPCA + 13,9% a.a. Aporte mínimo R$300K.",                                                                               observacoes_internas: "Exige comprovação de investimento prévio. Controle de caixa via tranches + acompanhamento técnico." },
  { id: "geminados",          nome: "Fundo Construção — Geminados",                nivel: "NIVEL_2", categoria: "Fundo Construção — 2 a 4 Unidades",                   cor: "#F472B6", emoji: "🏘️", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 500000,   valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 15, keywords_finalidade: ["geminado","duplex","2 unidades","3 unidades","4 unidades","sobrado"],               descricao: "2 a 4 unidades por lote. Estruturação via SPE. Taxa CDI + 9% a.a. Aporte mínimo R$500K.",                                                                                                    observacoes_internas: "SPE obrigatória. Análise de viabilidade pré-liberação." },
  { id: "fin_exterior",       nome: "Financiamento — Brasileiros no Exterior",     nivel: "NIVEL_2", categoria: "Financiamento Imobiliário Internacional",               cor: "#0EA5E9", emoji: "✈️", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: false, valor_minimo: 250000,   valor_maximo: null,      ltv_maximo: 0.70, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 20, keywords_finalidade: ["exterior","estrangeiro","internacional","remessa","brasileiro exterior"],           descricao: "Sem tradução juramentada. Renda internacional aceita. Taxa a partir de 11,25% a.a. LTV até 70%. Praças: SP, RJ, BH, Curitiba, POA, Floripa.",                                                observacoes_internas: "Comprometimento: PF 30% / PJ 10–40% fat. Aprovação com restrições via repasse automático." },
  { id: "cpr_agro",           nome: "CPR Agro",                                    nivel: "NIVEL_2", categoria: "Crédito para Agronegócio — CPR",                       cor: "#65A30D", emoji: "🌱", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 500000,   valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 20, keywords_finalidade: ["cpr","safra","colheita","producao rural","agro","produtor rural"],                  descricao: "Antecipação de CPR. Venda do produto convertida a valor presente imediato. Taxa a partir de 1,6% a.m. Aporte mínimo R$500K.",                                                                observacoes_internas: "Bom histórico no mercado de capitais gera taxas mais atrativas." },
  { id: "slb_agro",           nome: "Sale Leaseback Agro",                         nivel: "NIVEL_2", categoria: "Crédito Agro — Sale Leaseback",                        cor: "#4ADE80", emoji: "🌾", tipo_pessoa: "AMBOS", requer_imovel: true,  bloqueia_restricao: true,  valor_minimo: 2000000,  valor_maximo: 100000000, ltv_maximo: 0.70, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 25, keywords_finalidade: ["fazenda","rural","leaseback","arrendamento","slb agro"],                            descricao: "Fundo compra o imóvel rural. Cliente mantém arrendamento e recompra garantida. Taxa 12% a.a. + IPCA. LTV até 70%. Prazo 10 anos. R$2M–R$100M.",                                             observacoes_internas: "Custo: 6% mandato (mín. R$4M) + TAC 3%. Fazendas, galpões e salas comerciais aceitos." },
  { id: "op_int_cash",        nome: "Op. Internacional — Cash Collateral",         nivel: "NIVEL_2", categoria: "Operações Internacionais",                              cor: "#38BDF8", emoji: "🌎", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 10000000, valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["internacional","exterior","usd","dollar","business plan","cash collateral"],        descricao: "A partir de USD 2M. 25% em garantia bloqueada em banco AAA. Taxa 6–8% a.a. Prazo 10 anos + 3 carência. 12 tranches. Sem taxas antecipadas.",                                                observacoes_internas: "Requer Business Plan completo. Capital internacional sem internacionalizar a empresa." },
  { id: "cambio_pronto",      nome: "Câmbio Pronto",                               nivel: "NIVEL_2", categoria: "Câmbio e Operações Internacionais",                    cor: "#22D3EE", emoji: "💱", tipo_pessoa: "AMBOS", requer_imovel: false, bloqueia_restricao: false, valor_minimo: 0,        valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 10, keywords_finalidade: ["câmbio","cambio","remessa","pagamento exterior","dólar","dolar","usd"],             descricao: "Conversão imediata. Liquidação no mesmo dia ou em até 2 dias úteis. Remessas, pagamentos e investimentos no exterior. Taxa travada no ato.",                                                  observacoes_internas: "Custo: câmbio + spread + IOF. Suporte regulatório completo." },
  { id: "finimp",             nome: "FINIMP — Financiamento de Importações",       nivel: "NIVEL_2", categoria: "Câmbio — Importações",                                 cor: "#67E8F9", emoji: "🚢", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 0,        valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 10, keywords_finalidade: ["import","finimp","maquina importada","materia-prima","matéria-prima"],              descricao: "Crédito em moeda estrangeira. Isenção de IOF com hedge disponível. Prazo 90 dias–5 anos. Máquinas, matérias-primas e ativos do exterior.",                                                   observacoes_internas: "Condições mais competitivas que crédito doméstico. Hedge cambial disponível." },
  { id: "acc",                nome: "ACC — Adiantamento s/ Contrato de Câmbio",    nivel: "NIVEL_2", categoria: "Câmbio — Exportações Pré-Embarque",                    cor: "#34D399", emoji: "📦", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 0,        valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 10, keywords_finalidade: ["exporta","acc","pré-embarque","pre-embarque","embarque"],                          descricao: "Pré-embarque. Capital antecipado para produção antes do envio. Prazo até 360 dias. Taxas internacionais + risco-país.",                                                                      observacoes_internas: "Reduz pressão sobre o caixa. Independe dos prazos do importador." },
  { id: "ace",                nome: "ACE — Adiantamento s/ Cambiais Entregues",    nivel: "NIVEL_2", categoria: "Câmbio — Exportações Pós-Embarque",                    cor: "#6EE7B7", emoji: "🌊", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 0,        valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 10, keywords_finalidade: ["exporta","ace","pós-embarque","pos-embarque","cambiais"],                           descricao: "Pós-embarque. Vendas já enviadas ao exterior convertidas em liquidez imediata. Prazo 180–540 dias.",                                                                                          observacoes_internas: "Melhora o ciclo financeiro e mitiga risco externo." },
  // ── NÍVEL 3 — High Ticket ─────────────────────────────────────────────────
  { id: "cri_cash_collateral",nome: "CRI Cash Collateral",                         nivel: "NIVEL_3", categoria: "Securitização Imobiliária — Construtoras",              cor: "#F97316", emoji: "🏗️", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 5000000,  valor_maximo: 150000000, ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["construtora","incorporadora","cri","recebivel imobiliario","obra grande"],          descricao: "Para construtoras. Similar ao GERIC da CEF. Taxa 0,50–0,70% a.m. + CDI. R$5M–R$150M. Lastro em carteira de recebíveis (10–35% concluída/vendida).",                                        observacoes_internas: "Exige 10% concluída ou 35% vendida. Projetos residenciais, comerciais ou mistos de grande porte." },
  { id: "cri_inicio_obra",    nome: "Crédito Ponto / CRI Início de Obra",          nivel: "NIVEL_3", categoria: "Fundo Construção — Incorporadoras",                    cor: "#FB923C", emoji: "🏢", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 500000,   valor_maximo: 10000000,  ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 25, keywords_finalidade: ["alvará","alvara","inicio de obra","início de obra","spe","incorpora","cri inicio"],  descricao: "Para incorporadoras com alvará, LI e SPE. Capital estratégico imediato. Taxa a partir de 0,89% + IPCA. Até R$10M. Amortização Price.",                                                      observacoes_internas: "Exige alvará, licença de instalação (LI) e SPE já constituída." },
  { id: "bts_corporativo",    nome: "Construtoras BTS — Build-to-Suit",            nivel: "NIVEL_3", categoria: "Fundo Construção — Build-to-Suit Corporativo",          cor: "#EF4444", emoji: "🏭", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 2000000,  valor_maximo: 100000000, ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 25, keywords_finalidade: ["built to suit","build to suit","bts","corporativo","medida","galpão corporativo"],   descricao: "Build-to-Suit corporativo. Alinhamento técnico e financeiro sob medida. Taxas conforme projeto e contrato BTS. R$2M–R$100M.",                                                                observacoes_internas: "Taxas e critérios definidos conforme o projeto e contrato BTS." },
  { id: "incorporadoras",     nome: "Fundo Incorporadoras",                        nivel: "NIVEL_3", categoria: "Fundo Construção — Incorporadoras High Ticket",         cor: "#DC2626", emoji: "🏙️", tipo_pessoa: "PJ",    requer_imovel: false, bloqueia_restricao: true,  valor_minimo: 6000000,  valor_maximo: null,      ltv_maximo: 1.00, min_renda_mensal: 0,      min_faturamento_mensal: 0,       score_base: 30, keywords_finalidade: ["incorporadora","holding","lançamento","lancamento","multiplos","subholding"],         descricao: "Múltiplos lançamentos simultâneos. Holdings e subholdings. Taxa a partir de 6% + CDI. Aporte mínimo R$6M.",                                                                                  observacoes_internas: "Centralização societária via holdings. Eficiência operacional e segurança jurídica." },
  { id: "op_int_garantia",    nome: "Op. Internacional — Garantia Imobiliária",    nivel: "NIVEL_3", categoria: "Operações Internacionais High Ticket",                  cor: "#7C3AED", emoji: "🌐", tipo_pessoa: "PJ",    requer_imovel: true,  bloqueia_restricao: true,  valor_minimo: 50000000, valor_maximo: null,      ltv_maximo: 0.70, min_renda_mensal: 0,      min_faturamento_mensal: 2083333, score_base: 25, keywords_finalidade: ["internacional high ticket","usd 10m","garantia imobiliaria internacional"],           descricao: "A partir de USD 10M. Faturamento mínimo R$25M/ano. Taxa 6–8% a.a. Prazo 10 anos + 2 carência. Liberação única. Sem IOF.",                                                                   observacoes_internas: "Análise pela capacidade do Business Plan futuro. LTV até 70% com exceções." },
];

export async function GET() {
  const { data, error } = await svc()
    .from("regras_linhas_credito")
    .select("*")
    .order("nivel")
    .order("id");

  // Se tabela vazia, retorna defaults
  if (!error && (!data || data.length === 0)) {
    return NextResponse.json({ regras: DEFAULT_REGRAS });
  }
  if (error) return NextResponse.json({ regras: DEFAULT_REGRAS });

  return NextResponse.json({ regras: data });
}

export async function PATCH(req: NextRequest) {
  const { user, profile } = await getUser();
  if (!user) return NextResponse.json({ error: "Não autorizado" }, { status: 401 });
  if (!ADMIN_ROLES.includes(profile?.role ?? "")) {
    return NextResponse.json({ error: "Sem permissão" }, { status: 403 });
  }

  const body = await req.json();
  const { id, ...fields } = body;
  if (!id) return NextResponse.json({ error: "ID obrigatório" }, { status: 400 });

  // Upsert — cria ou atualiza
  const { data, error } = await svc()
    .from("regras_linhas_credito")
    .upsert({ id, ...fields, updated_at: new Date().toISOString() })
    .select()
    .single();

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true, regra: data });
}

// Seed inicial — popula a tabela com defaults
export async function POST() {
  const { user, profile } = await getUser();
  if (!user) return NextResponse.json({ error: "Não autorizado" }, { status: 401 });
  if (profile?.role !== "ADMIN") return NextResponse.json({ error: "Sem permissão" }, { status: 403 });

  const { error } = await svc()
    .from("regras_linhas_credito")
    .upsert(DEFAULT_REGRAS.map(r => ({ ...r, updated_at: new Date().toISOString() })));

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true, seeded: DEFAULT_REGRAS.length });
}
