ALTER TABLE sector_5w2h DROP CONSTRAINT IF EXISTS sector_5w2h_sector_check;
ALTER TABLE sector_5w2h ADD CONSTRAINT sector_5w2h_sector_check
  CHECK (sector IN ('MA','CREDITO','CONSORCIO','BOLSA_ATIVOS','MARKETPLACE','CREDITO_INTERNACIONAL','ASSINATURAS'));

ALTER TABLE sector_swot DROP CONSTRAINT IF EXISTS sector_swot_sector_check;
ALTER TABLE sector_swot ADD CONSTRAINT sector_swot_sector_check
  CHECK (sector IN ('MA','CREDITO','CONSORCIO','BOLSA_ATIVOS','MARKETPLACE','CREDITO_INTERNACIONAL','ASSINATURAS'));

ALTER TABLE sector_goals DROP CONSTRAINT IF EXISTS sector_goals_sector_check;
ALTER TABLE sector_goals ADD CONSTRAINT sector_goals_sector_check
  CHECK (sector IN ('MA','CREDITO','CONSORCIO','BOLSA_ATIVOS','MARKETPLACE','CREDITO_INTERNACIONAL','ASSINATURAS'));
