-- Mandato de Crédito (09/10/2026, pedido do Hamilton): minutas PF e PJ do mandato
-- enviado ao cliente pelo botão "Mandato" do modal da proposta (Mesa Operacional).
-- Texto revisado juridicamente (multa de 1% por desistência após a aprovação,
-- Remuneração de Sucesso sobre o valor líquido liberado). Entram em revisão:
-- só geram contrato depois de aprovadas em Central de Contratos > Minutas.
-- Variáveis: {{contratante_qualificacao}}, {{percentual_mandato}}, {{data_geracao_extenso}}.

insert into contract_templates (template_name, vertical, body_text_raw, variables_map, version, is_active, approval_status, editable_sections, contract_series, review_round, origem, requires_counterparty_signature, head_declared_in_body, created_by)
select 'Mandato de Crédito (Cliente PF)', 'credito', $mandato$<h1>INSTRUMENTO PARTICULAR DE MANDATO E PRESTAÇÃO DE SERVIÇOS DE ASSESSORIA E INTERMEDIAÇÃO DE OPERAÇÕES DE CRÉDITO</h1>
<p>Pelo presente instrumento particular, de um lado:</p>
<p><strong>V3 PARTNERS SOLUÇÕES LTDA.</strong>, sociedade empresária limitada, inscrita no CNPJ sob o nº 14.219.287/0001-50, registrada na JUCERJA sob o NIRE nº 33.2.0898614-3, com sede na Rua Visconde de Pirajá, nº 414, sala 718, Ipanema, Rio de Janeiro/RJ, CEP 22.410-002, endereço eletrônico suporte@v3partners.com.br, neste ato representada, na forma de seu contrato social, por seu sócio administrador <strong>JOÃO LEMOS NETTO</strong>, brasileiro, divorciado, empresário, nascido em 13/06/1978, portador da carteira de identidade nº 11734474-7 IFP/RJ, inscrito no CPF sob o nº 078.678.257-97, residente e domiciliado na Rua Desembargador Oscar Tenório, nº 95, apto. 102, Recreio dos Bandeirantes, Rio de Janeiro/RJ, CEP 22975-110, doravante designada simplesmente <strong>CONTRATADA</strong> ou <strong>V3</strong>;</p>
<p>e, de outro lado,</p>
<p>{{contratante_qualificacao}}</p>
<p>Sendo CONTRATADA e CONTRATANTE designadas, em conjunto, “<strong>Partes</strong>” e, isoladamente, “<strong>Parte</strong>”, e sendo este instrumento designado “<strong>MANDATO</strong>”.</p>
<h2>CONSIDERANDOS</h2>
<p>I – a CONTRATANTE tem interesse em obter crédito e recursos para suas atividades ou necessidades;</p>
<p>II – a CONTRATADA é empresa de assessoria e intermediação de crédito que se relaciona com Instituições Financeiras Originadoras do Crédito e tem condições de aproximar a CONTRATANTE desses potenciais fornecedores de recursos, bem como de estruturar e defender a operação perante eles;</p>
<p>III – a CONTRATANTE deseja contratar a CONTRATADA para atuar em seu interesse, como assessora independente, na identificação, estruturação, negociação e intermediação de Operações de Crédito;</p>
<p>IV – a análise de crédito, o levantamento e a conferência documental, a estruturação e a defesa de crédito exigem a mobilização de equipe técnica e comercial e geram custos para a CONTRATADA desde o início dos trabalhos, independentemente do resultado;</p>
<p>as Partes resolvem celebrar o presente MANDATO, que se regerá pelas cláusulas e condições abaixo e, no que couber, pelos arts. 653 e seguintes (mandato) e 722 e seguintes (corretagem) do Código Civil.</p>
<h2>CLÁUSULA 1 – DEFINIÇÕES</h2>
<p>1.1. Sem prejuízo de outras definições constantes deste MANDATO, os termos abaixo, quando iniciados em letra maiúscula, terão os seguintes significados:</p>
<p><strong>“Operação de Crédito” ou “Operação”</strong>: qualquer empréstimo, financiamento, adiantamento, antecipação de recebíveis, consórcio contemplado, crédito com garantia (inclusive imobiliária – home equity), capital de giro, emissão de título de crédito ou valor mobiliário, cessão de créditos ou qualquer outra transação de natureza creditícia ou de captação de recursos celebrada pela <strong>CONTRATANTE</strong> (ou por suas Afiliadas, ou por terceiros em seu benefício) com Instituição Financeira Originadora do Crédito, incluindo renovações, aditamentos, prorrogações e novas tranches;</p>
<p><strong>“Afiliadas”</strong>: o cônjuge ou companheiro(a) da CONTRATANTE, seus ascendentes e descendentes e as sociedades em que a CONTRATANTE ou tais pessoas detenham participação de controle;</p>
<p><strong>“Instituições Financeiras Originadoras do Crédito” ou “Instituições”</strong>: bancos, cooperativas de crédito, sociedades de crédito direto (SCD), financeiras, fundos de investimento (inclusive FIDCs), securitizadoras, administradoras de consórcio, gestoras (assets), plataformas de crédito e quaisquer outras entidades que concedam ou estruturem crédito, que mantenham ou venham a manter relacionamento com a CONTRATADA;</p>
<p><strong>“Briefing”</strong>: o formulário de briefing, as entrevistas de crédito e as informações prestadas pela CONTRATANTE que delimitam o crédito pretendido (valor, finalidade, prazo, taxa-alvo e garantias disponíveis);</p>
<p><strong>“Aprovação”</strong>: a comunicação, pela Instituição, por escrito ou por meio eletrônico (e-mail, plataforma, sistema ou aplicativo de mensagens), de que o crédito foi aprovado em favor da CONTRATANTE, ainda que sujeita a condições precedentes usuais de mercado (tais como constituição e registro de garantias, avaliação de bens, apresentação de certidões e assinatura dos instrumentos), cujo teor tenha sido repassado pela CONTRATADA à CONTRATANTE;</p>
<p><strong>“Valor Aprovado”</strong>: o valor do crédito constante da Aprovação; havendo mais de uma Aprovação, o daquela escolhida pela CONTRATANTE ou, na ausência de escolha, o da Aprovação de maior valor;</p>
<p><strong>“Valor da Operação”</strong>: o <strong>valor líquido efetivamente liberado</strong> em cada Operação, à vista ou em parcelas, assim entendido o montante creditado em conta de titularidade da CONTRATANTE ou de suas Afiliadas, ou destinado, por sua ordem, à quitação de dívidas, ao pagamento de fornecedores ou a qualquer outra finalidade definida na estruturação, após as deduções retidas na fonte pela Instituição no ato da liberação (tais como IOF, tarifas, seguros, taxas de abertura de crédito e custos de registro). Não serão deduzidos do Valor da Operação (a) os valores que a Instituição, por ordem da CONTRATANTE ou por exigência da estruturação, pagar diretamente a credores ou fornecedores da CONTRATANTE, os quais integram o valor liberado; nem (b) os valores pagos pela CONTRATANTE a terceiros após a liberação, tais como avaliações, despesas cartorárias, regularizações e honorários de assessores. Não integram o Valor da Operação os juros remuneratórios e demais encargos financeiros que incidirão ao longo do prazo da Operação;</p>
<p><strong>“Data da Concretização”</strong>: a data em que os recursos forem efetivamente disponibilizados à CONTRATANTE ou por sua ordem, ou, em operações de antecipação de recebíveis, a data de formalização do limite; em liberações por tranches, a data de cada liberação;</p>
<p><strong>“Remuneração de Sucesso”</strong>: a remuneração devida à CONTRATADA em razão da concretização da Operação, nos termos da Cláusula 3.</p>
<p>1.2. Em operações estruturadas por meio de consórcio, o Valor da Operação corresponderá ao valor do crédito contemplado e efetivamente disponibilizado, e não à soma das cartas de crédito adquiridas.</p>
<h2>CLÁUSULA 2 – DO OBJETO E DA NATUREZA DOS SERVIÇOS</h2>
<p>2.1. A CONTRATANTE contrata a CONTRATADA para identificar, apresentar e intermediar relações comerciais com Instituições Financeiras Originadoras do Crédito, bem como para analisar, estruturar, negociar e defender Operações de Crédito em favor da CONTRATANTE, mediante a remuneração prevista na Cláusula 3.</p>
<p>2.2. Para tanto, a CONTRATADA prestará os serviços com ética, diligência e transparência, competindo-lhe, conforme a necessidade de cada Operação:</p>
<p>a) analisar os dados e documentos necessários à melhor estruturação da Operação, com base no Briefing;</p>
<p>b) estudar o perfil da CONTRATANTE para compreender suas necessidades e requisitos;</p>
<p>c) identificar e apresentar à CONTRATANTE as alternativas de crédito disponíveis no mercado mais adequadas ao seu perfil;</p>
<p>d) analisar as ofertas preliminares e finais apresentadas pelas Instituições;</p>
<p>e) definir a estratégia de negociação e de recebimento de ofertas;</p>
<p>f) apoiar a CONTRATANTE na organização e obtenção de documentos e certidões e nos procedimentos de elegibilidade;</p>
<p>g) estruturar e apresentar a Defesa de Crédito da CONTRATANTE perante as Instituições, inclusive com materiais complementares elaborados em conjunto com a CONTRATANTE;</p>
<p>h) representar a CONTRATANTE perante as Instituições nos processos de due diligence;</p>
<p>i) definir, com os profissionais indicados pela CONTRATANTE, a estrutura da Operação e, quando solicitado, interagir com seus assessores jurídicos na revisão dos instrumentos;</p>
<p>j) coordenar visitas, reuniões e o cronograma da Operação; e</p>
<p>k) conduzir as negociações finais com as Instituições, buscando os melhores termos possíveis para a CONTRATANTE.</p>
<p>2.3. <strong>Poderes.</strong> Para a execução do objeto, a CONTRATANTE outorga à CONTRATADA poderes para representá-la perante as Instituições, com a finalidade de apresentar seu cadastro e documentos, solicitar análises e propostas, receber comunicações e negociar condições comerciais. Não estão compreendidos neste MANDATO poderes para assinar instrumentos de crédito, constituir garantias, receber ou dar quitação de recursos em nome da CONTRATANTE, atos que dependem sempre de manifestação direta da própria CONTRATANTE.</p>
<p>2.4. <strong>Obrigação de meio.</strong> As obrigações da CONTRATADA são de meio e não de resultado. A concessão do crédito, as taxas, prazos, garantias e demais condições são decididos exclusivamente pelas Instituições, segundo suas políticas internas, não havendo garantia de aprovação, de valor ou de condições.</p>
<p>2.5. <strong>Independência.</strong> A CONTRATADA atua, no âmbito deste MANDATO, como assessora contratada pela CONTRATANTE e no interesse desta. A CONTRATADA não é instituição financeira, não capta recursos do público, não concede crédito e não recebe, em nenhuma hipótese, os recursos da Operação em nome da CONTRATANTE.</p>
<h2>CLÁUSULA 3 – DA REMUNERAÇÃO</h2>
<p>3.1. Como contraprestação pelos serviços, a CONTRATANTE pagará à CONTRATADA Remuneração de Sucesso equivalente a <strong>{{percentual_mandato}} do Valor da Operação</strong>, em moeda corrente nacional.</p>
<p>3.2. A Remuneração de Sucesso é devida sobre cada Operação (inclusive renovações, aditamentos, prorrogações, recompras de garantia e novas Operações) celebrada com Instituição apresentada pela CONTRATADA ou em cuja negociação a CONTRATADA tenha atuado. Considera-se que a CONTRATADA atuou na negociação quando prestou, ou esteve disponível para prestar, os serviços da Cláusula 2.</p>
<p>3.3. <strong>Prazo e forma de pagamento.</strong> A Remuneração de Sucesso será paga em até 2 (dois) dias úteis contados da Data da Concretização, por PIX ou transferência para a conta de titularidade da CONTRATADA – PIX CNPJ 14.219.287/0001-50, Banco 403 – Cora SCD, agência 0001, conta 7175979-1 –, servindo o comprovante como recibo. A CONTRATADA emitirá a nota fiscal correspondente em até 1 (um) dia útil após ser informada da concretização.</p>
<p>3.4. <strong>Dever de informar.</strong> A CONTRATANTE informará à CONTRATADA, em até 1 (um) dia útil, a liberação de quaisquer recursos e a assinatura de quaisquer instrumentos relativos à Operação, apresentando, quando solicitado, cópia do contrato e do comprovante de liberação.</p>
<p>3.5. <strong>Pagamento direto pela Instituição.</strong> A CONTRATANTE autoriza, em caráter irrevogável e irretratável, que a Instituição, quando operacionalmente viável, retenha e repasse diretamente à CONTRATADA o valor da Remuneração de Sucesso por ocasião da liberação dos recursos, o que importará quitação da respectiva parcela.</p>
<p>3.6. <strong>Tranches.</strong> Em liberações parceladas, a Remuneração de Sucesso será devida proporcionalmente sobre cada parcela, no prazo da cláusula 3.3 contado de cada liberação. Se a CONTRATANTE, por sua vontade, deixar de utilizar o saldo aprovado e não liberado, aplica-se a esse saldo a Cláusula 4.</p>
<p>3.7. <strong>Antecipação de recebíveis.</strong> Nas operações de antecipação de recebíveis, (a) a Remuneração de Sucesso prevista na cláusula 3.1 incidirá sobre o valor total do limite aprovado e formalizado com a Instituição ou cessionária, independentemente de sua utilização total ou parcial, sendo devida na Data da Concretização; e (b) a CONTRATANTE pagará ainda à CONTRATADA <strong>0,20% (zero vírgula vinte por cento)</strong> sobre cada valor efetivamente antecipado no âmbito desse limite e de suas renovações, em até 2 (dois) dias úteis de cada antecipação.</p>
<p>3.8. <strong>Período de cauda.</strong> A Remuneração de Sucesso será devida, ainda, sobre Operações celebradas com Instituição apresentada pela CONTRATADA em até <strong>24 (vinte e quatro) meses</strong> após o término ou a rescisão deste MANDATO, qualquer que seja o motivo, ainda que a Operação seja celebrada diretamente pela CONTRATANTE, por suas Afiliadas ou por intermédio de terceiros (art. 727 do Código Civil).</p>
<p>3.9. <strong>Tributos.</strong> A remuneração aqui prevista é bruta. Cada Parte responderá pelos tributos de que for contribuinte, observadas as retenções na fonte obrigatórias por lei, que serão destacadas na nota fiscal.</p>
<p>3.10. <strong>Mora.</strong> O atraso em qualquer pagamento sujeitará a Parte inadimplente a multa moratória de 2% (dois por cento), juros de mora de 1% (um por cento) ao mês, pro rata die, e correção monetária pela variação do IPCA/IBGE, desde o vencimento até o efetivo pagamento, além de honorários advocatícios de 10% (dez por cento) em caso de cobrança extrajudicial por advogado, direito que se assegura reciprocamente a ambas as Partes.</p>
<p>3.11. O débito vencido e não pago por mais de 30 (trinta) dias poderá ser levado a protesto e inscrito em cadastros de proteção ao crédito, observadas as comunicações prévias exigidas em lei.</p>
<p>3.12. <strong>Revisão.</strong> Se, antes da Aprovação, ocorrerem alterações relevantes de mercado que tornem inadequada a remuneração pactuada, as Partes poderão negociar de boa-fé novos termos, por escrito. Em nenhuma hipótese haverá redução da remuneração de Operação já aprovada ou concretizada. Não havendo acordo, qualquer Parte poderá resilir este MANDATO nos termos da Cláusula 11, preservados os direitos previstos nas Cláusulas 3 e 4.</p>
<h2>CLÁUSULA 4 – DA DESISTÊNCIA APÓS A APROVAÇÃO (MULTA DE 1%)</h2>
<p>4.1. <strong>Considerando que, até a Aprovação, a CONTRATADA terá mobilizado equipe técnica e comercial, realizado a análise de crédito, o levantamento e a conferência da documentação, a estruturação da Operação, a elaboração da Defesa de Crédito e a interlocução com as Instituições, as Partes ajustam que, ocorrida a Aprovação, a desistência da CONTRATANTE a obrigará a pagar à CONTRATADA multa compensatória equivalente a 1% (um por cento) do Valor Aprovado (“Multa por Desistência”), a título de remuneração pelo trabalho de análise, documentação e equipe efetivamente prestado.</strong></p>
<p>4.2. Considera-se desistência, para os fins desta Cláusula, a ocorrência de qualquer das seguintes hipóteses após a Aprovação:</p>
<p>a) comunicação da CONTRATANTE, por qualquer meio, de que não pretende prosseguir com a Operação, inclusive mediante resilição deste MANDATO;</p>
<p>b) recusa ou omissão, sem justa causa, em assinar os instrumentos da Operação no prazo de 10 (dez) dias úteis contados do seu recebimento;</p>
<p>c) não apresentação de documentos, garantias ou certidões, ou descumprimento de condições precedentes de responsabilidade da CONTRATANTE, no prazo concedido pela Instituição, dando causa à caducidade ou ao cancelamento da Aprovação;</p>
<p>d) ausência de resposta às comunicações da CONTRATADA por mais de 15 (quinze) dias corridos, após notificação específica com menção expressa a esta Cláusula; ou</p>
<p>e) contratação, em substituição à Operação aprovada, de operação de mesma finalidade com instituição não apresentada pela CONTRATADA.</p>
<p>4.3. A Multa por Desistência tem natureza de cláusula penal compensatória, prefixa as perdas e danos decorrentes dos custos de estruturação já incorridos e é exigível independentemente de prova de prejuízo (arts. 408, 409 e 416 do Código Civil), reconhecendo as Partes, desde já, sua proporcionalidade ao trabalho executado (art. 413 do Código Civil).</p>
<p>4.4. A Multa por Desistência será paga em até 10 (dez) dias corridos contados da notificação da CONTRATADA, na forma da cláusula 3.3, sujeitando-se o atraso à cláusula 3.10.</p>
<p>4.5. A Multa por Desistência não se cumula com a Taxa Administrativa da cláusula 6.4; tendo esta sido paga, seu valor será abatido daquela.</p>
<p>4.6. Se, após a desistência, a Operação, ou outra de mesma finalidade, vier a ser celebrada com Instituição apresentada pela CONTRATADA no prazo da cláusula 3.8, será devida a Remuneração de Sucesso integral, abatido o valor já pago a título de Multa por Desistência.</p>
<p>4.7. <strong>A CONTRATANTE declara ter lido e compreendido esta Cláusula 4, redigida em destaque para permitir sua imediata e fácil compreensão, e que com ela concorda expressamente.</strong></p>
<h2>CLÁUSULA 5 – DA NÃO EXCLUSIVIDADE E DA NÃO CIRCUNVENÇÃO</h2>
<p>5.1. Este MANDATO não é exclusivo. A CONTRATANTE poderá buscar crédito diretamente ou por meio de terceiros, sem que isso gere remuneração à CONTRATADA, <strong>desde que</strong> a Operação não seja celebrada com Instituição apresentada pela CONTRATADA, ressalvado o disposto na Cláusula 4.</p>
<p>5.2. A CONTRATANTE obriga-se a não contornar a CONTRATADA, direta ou indiretamente, inclusive por meio de Afiliadas ou de outros intermediários, para celebrar Operação com Instituição apresentada pela CONTRATADA, sob pena de pagamento da Remuneração de Sucesso integral, como se a Operação tivesse sido intermediada pela CONTRATADA.</p>
<p>5.3. Considera-se apresentada pela CONTRATADA a Instituição à qual o cadastro, a proposta ou a Defesa de Crédito da CONTRATANTE tenha sido submetido pela CONTRATADA, ou cuja identidade a CONTRATADA tenha revelado à CONTRATANTE no curso deste MANDATO, o que poderá ser comprovado por qualquer meio, inclusive e-mails e mensagens eletrônicas.</p>
<h2>CLÁUSULA 6 – DAS OBRIGAÇÕES DAS PARTES</h2>
<p>6.1. As Partes prestarão contas uma à outra sempre que solicitado, com transparência sobre os atos relacionados a este MANDATO.</p>
<p>6.2. A CONTRATADA informará a CONTRATANTE sobre os procedimentos adotados e sobre fatos que possam afetar a prestação dos serviços.</p>
<p>6.3. A CONTRATANTE fornecerá à CONTRATADA, de forma clara, correta, completa e tempestiva, as informações e documentos necessários, respondendo por sua veracidade, exatidão e atualização, e encaminhará toda a documentação constante do checklist disponibilizado pela CONTRATADA no prazo de <strong>30 (trinta) dias corridos</strong> contados da assinatura deste MANDATO.</p>
<p>6.4. <strong>Taxa Administrativa.</strong> O não envio da documentação completa no prazo da cláusula 6.3, sem justificativa aceita por escrito pela CONTRATADA, sujeitará a CONTRATANTE ao pagamento de taxa administrativa equivalente a 1% (um por cento) do valor do crédito solicitado no Briefing, destinada à compensação dos custos administrativos e operacionais já incorridos, a ser paga em até 10 (dez) dias corridos contados do término daquele prazo ou da comunicação formal do descumprimento, o que ocorrer por último.</p>
<p>6.5. A CONTRATADA não responde pela negativa de crédito, pelas condições impostas pelas Instituições ou por inconsistências na documentação apresentada pela CONTRATANTE.</p>
<p>6.6. A Parte que utilizar informações ou documentos falsos, adulterados ou manipulados responderá por todas as perdas, danos, custos e despesas (inclusive honorários advocatícios) daí decorrentes, isentando a outra Parte de qualquer responsabilidade, sem prejuízo da rescisão imediata deste MANDATO.</p>
<p>6.7. Nenhuma das Partes responde por atos praticados pela outra, ou por seus prepostos, em desacordo com este MANDATO.</p>
<h2>CLÁUSULA 7 – DA PROTEÇÃO DE DADOS PESSOAIS</h2>
<p>7.1. As Partes tratarão dados pessoais em conformidade com a Lei nº 13.709/2018 (LGPD), atuando cada uma como controladora independente dos dados que tratar para suas próprias finalidades.</p>
<p>7.2. Os dados pessoais da CONTRATANTE, de seu cônjuge ou companheiro(a) e de eventuais garantidores serão tratados para a execução deste MANDATO e de procedimentos preliminares a ele relacionados (art. 7º, V, LGPD), para a proteção do crédito (art. 7º, X), para o cumprimento de obrigações legais e regulatórias (art. 7º, II) e para o exercício regular de direitos (art. 7º, VI).</p>
<p>7.3. A CONTRATANTE autoriza a CONTRATADA a compartilhar seus dados e documentos com as Instituições, com prestadores de serviço necessários à Operação (avaliadores, cartórios, assessores) e com os parceiros previstos na cláusula 13.1, exclusivamente para as finalidades deste MANDATO, e autoriza a CONTRATADA e as Instituições a consultar o Sistema de Informações de Crédito do Banco Central (SCR) e bases de birôs de crédito a seu respeito.</p>
<p>7.4. A CONTRATADA adotará medidas técnicas e administrativas aptas a proteger os dados pessoais contra acessos não autorizados e situações ilícitas, comunicará à CONTRATANTE incidentes de segurança que possam acarretar risco ou dano relevante aos titulares e cooperará no atendimento a solicitações de titulares.</p>
<p>7.5. Encerrado o MANDATO, os dados serão eliminados, ressalvada a conservação necessária ao cumprimento de obrigação legal ou regulatória (inclusive de prevenção à lavagem de dinheiro) e ao exercício regular de direitos (art. 16, LGPD).</p>
<h2>CLÁUSULA 8 – DA CONFIDENCIALIDADE</h2>
<p>8.1. Serão consideradas Informações Confidenciais todas as informações, dados, documentos e materiais, de qualquer natureza e em qualquer meio, revelados por uma Parte à outra em razão deste MANDATO, inclusive os termos deste instrumento, as propostas e condições obtidas junto às Instituições, a identidade dos contatos da CONTRATADA nas Instituições e os materiais de Defesa de Crédito.</p>
<p>8.2. Não são confidenciais as informações que (a) sejam ou se tornem de domínio público sem culpa da Parte receptora; (b) já estivessem licitamente em poder da Parte receptora; ou (c) sejam recebidas de terceiros sem dever de sigilo.</p>
<p>8.3. A CONTRATADA poderá compartilhar Informações Confidenciais da CONTRATANTE com as Instituições, com os parceiros e prestadores de serviço referidos na cláusula 7.3 e com seus sócios, empregados e colaboradores, na medida necessária à execução deste MANDATO, desde que sujeitos a dever de sigilo equivalente.</p>
<p>8.4. A CONTRATANTE não poderá divulgar a terceiros, nem utilizar para fins diversos deste MANDATO, as propostas, condições, contatos e materiais fornecidos pela CONTRATADA.</p>
<p>8.5. A Parte obrigada por lei, ordem judicial ou autoridade competente a revelar Informação Confidencial comunicará o fato à outra Parte, quando legalmente permitido, e revelará apenas o estritamente necessário. Não configura violação de sigilo a comunicação feita pela CONTRATADA às autoridades competentes em cumprimento à legislação de prevenção à lavagem de dinheiro.</p>
<p>8.6. As obrigações desta Cláusula vigorarão durante o MANDATO e por 5 (cinco) anos após seu término.</p>
<h2>CLÁUSULA 9 – ANTICORRUPÇÃO E PREVENÇÃO À LAVAGEM DE DINHEIRO</h2>
<p>9.1. As Partes cumprirão a Lei nº 12.846/2013 (Lei Anticorrupção), a Lei nº 9.613/1998 (Lei de Lavagem de Dinheiro) e demais normas aplicáveis, abstendo-se de oferecer, prometer ou pagar, direta ou indiretamente, vantagem indevida a agente público ou privado, inclusive a empregados das Instituições.</p>
<p>9.2. A CONTRATANTE fornecerá as informações cadastrais e de conheça-seu-cliente solicitadas pela CONTRATADA ou pelas Instituições, inclusive quanto à origem de recursos e à condição de pessoa exposta politicamente.</p>
<p>9.3. As Partes declaram que não se encontram sob investigação, processo ou condenação por corrupção, lavagem de dinheiro ou financiamento ao terrorismo, nem sujeitas a sanções ou listas restritivas nacionais ou internacionais.</p>
<p>9.4. A violação desta Cláusula autoriza a rescisão imediata do MANDATO, respondendo a Parte infratora pelas perdas e danos causados.</p>
<h2>CLÁUSULA 10 – DAS DECLARAÇÕES DAS PARTES</h2>
<p>10.1. As Partes declaram que seus signatários estão devidamente autorizados a celebrar este MANDATO, que este constitui obrigação válida, eficaz e exequível e que sua celebração não viola contrato, decisão judicial ou administrativa a que estejam sujeitas.</p>
<p>10.2. A CONTRATADA declara possuir capacidade técnica e estrutura para prestar os serviços conforme as boas práticas de mercado.</p>
<p>10.3. A CONTRATANTE declara que as informações do Briefing são verdadeiras e que não omitiu fato relevante para a análise de crédito.</p>
<h2>CLÁUSULA 11 – DA VIGÊNCIA E DA RESCISÃO</h2>
<p>11.1. Este MANDATO vigora por prazo indeterminado a partir de sua assinatura e poderá ser resilido por qualquer Parte, sem justa causa, mediante notificação escrita com antecedência mínima de 30 (trinta) dias.</p>
<p>11.2. O MANDATO poderá ser rescindido de imediato, mediante notificação, em caso de (a) descumprimento contratual não sanado em 15 (quinze) dias contados da notificação; (b) falência, recuperação judicial ou extrajudicial ou insolvência da outra Parte; (c) uso de informações ou documentos falsos; ou (d) violação da Cláusula 9.</p>
<p>11.3. A resilição ou rescisão não prejudica (a) a Remuneração de Sucesso das Operações concretizadas ou em curso, nem o período de cauda da cláusula 3.8; (b) a Multa por Desistência, se a resilição pela CONTRATANTE ocorrer após a Aprovação ou se a rescisão decorrer de culpa da CONTRATANTE após a Aprovação; e (c) as obrigações das Cláusulas 7, 8 e 9, que sobrevivem ao término do MANDATO.</p>
<p>11.4. A Parte que der causa à rescisão indenizará a outra pelas perdas e danos comprovados, inclusive honorários advocatícios, observada a Cláusula 12.</p>
<p>11.5. <strong>Direito de arrependimento. Por se tratar de contratação celebrada fora do estabelecimento comercial, a CONTRATANTE poderá desistir deste MANDATO no prazo de 7 (sete) dias contados de sua assinatura, sem qualquer ônus, mediante comunicação à CONTRATADA (art. 49 do Código de Defesa do Consumidor).</strong></p>
<h2>CLÁUSULA 12 – DA RESPONSABILIDADE</h2>
<p>12.1. A CONTRATADA responde pelos serviços que presta, nos termos da lei, não respondendo pelas decisões de crédito e condições estabelecidas pelas Instituições, que são terceiros alheios ao seu controle, nos termos da cláusula 2.4.</p>
<h2>CLÁUSULA 13 – DAS DISPOSIÇÕES GERAIS</h2>
<p>13.1. A CONTRATADA poderá substabelecer, com reserva de iguais poderes, e contratar ou associar-se a terceiros – inclusive Partners credenciados à rede V3, correspondentes e assessores – para a execução deste MANDATO, independentemente de autorização prévia, permanecendo responsável perante a CONTRATANTE e arcando com a remuneração de tais terceiros.</p>
<p>13.2. As comunicações entre as Partes serão feitas por escrito, para os endereços físicos ou eletrônicos indicados no preâmbulo, sendo válidas as realizadas por e-mail e por aplicativo de mensagens aos números informados pelas Partes. Alterações de endereço deverão ser comunicadas por escrito.</p>
<p>13.3. Este MANDATO constitui o acordo integral entre as Partes sobre seu objeto, substitui entendimentos anteriores e somente poderá ser alterado por aditivo escrito.</p>
<p>13.4. A tolerância ou o não exercício de qualquer direito não importará renúncia, novação ou alteração do pactuado. A renúncia somente valerá se expressa e por escrito, interpretando-se restritivamente.</p>
<p>13.5. A nulidade de qualquer disposição não afetará as demais, que permanecerão válidas.</p>
<p>13.6. Nenhuma Parte poderá ceder este MANDATO sem consentimento escrito da outra, salvo a cessão, pela CONTRATADA, dos créditos dele decorrentes.</p>
<p>13.7. Este MANDATO não gera vínculo societário, empregatício ou de representação comercial entre as Partes ou entre uma Parte e os prepostos da outra.</p>
<p>13.8. Este MANDATO, assinado pelas Partes, constitui título executivo extrajudicial (art. 784, III e § 4º, do Código de Processo Civil), obrigando as Partes e seus sucessores a qualquer título, sendo líquidas e certas as obrigações de pagamento nele previstas, apuradas mediante simples cálculo aritmético sobre o Valor da Operação ou o Valor Aprovado.</p>
<p>13.9. As Partes reconhecem a validade da assinatura eletrônica deste instrumento, por certificado ICP-Brasil, pela plataforma gov.br ou por plataforma de assinatura eletrônica que assegure a autoria e a integridade do documento (art. 10, § 2º, da MP nº 2.200-2/2001 e Lei nº 14.063/2020), dispensada a assinatura de testemunhas nos termos do art. 784, § 4º, do Código de Processo Civil.</p>
<h2>CLÁUSULA 14 – DA LEI APLICÁVEL E DO FORO</h2>
<p>14.1. Este MANDATO é regido pelas leis da República Federativa do Brasil. Fica eleito o foro da Comarca da Capital do Estado do Rio de Janeiro, local da sede da CONTRATADA, para dirimir quaisquer controvérsias dele decorrentes, ressalvado à CONTRATANTE o direito de demandar e ser demandada no foro de seu domicílio, nos termos do Código de Defesa do Consumidor.</p>
<p>E, por estarem justas e contratadas, as Partes assinam este instrumento eletronicamente, para que produza seus efeitos legais.</p>
<p>Rio de Janeiro, {{data_geracao_extenso}}.</p>$mandato$, '[{"key": "contratante_qualificacao", "label": "qualificação da contratante", "source": "auto"}, {"key": "percentual_mandato", "label": "percentual do mandato", "source": "auto"}, {"key": "data_geracao_extenso", "label": "data geracao extenso", "source": "auto"}]'::jsonb, 1, true, 'em_revisao', '[]'::jsonb, 'V3C-MAN', 1, 'manual', true, false, '75c6cac4-8d30-436e-b9a6-d5d494d7470b'
where not exists (select 1 from contract_templates where template_name = 'Mandato de Crédito (Cliente PF)');

insert into contract_templates (template_name, vertical, body_text_raw, variables_map, version, is_active, approval_status, editable_sections, contract_series, review_round, origem, requires_counterparty_signature, head_declared_in_body, created_by)
select 'Mandato de Crédito (Cliente PJ)', 'credito', $mandato$<h1>INSTRUMENTO PARTICULAR DE MANDATO E PRESTAÇÃO DE SERVIÇOS DE ASSESSORIA E INTERMEDIAÇÃO DE OPERAÇÕES DE CRÉDITO</h1>
<p>Pelo presente instrumento particular, de um lado:</p>
<p><strong>V3 PARTNERS SOLUÇÕES LTDA.</strong>, sociedade empresária limitada, inscrita no CNPJ sob o nº 14.219.287/0001-50, registrada na JUCERJA sob o NIRE nº 33.2.0898614-3, com sede na Rua Visconde de Pirajá, nº 414, sala 718, Ipanema, Rio de Janeiro/RJ, CEP 22.410-002, endereço eletrônico suporte@v3partners.com.br, neste ato representada, na forma de seu contrato social, por seu sócio administrador <strong>JOÃO LEMOS NETTO</strong>, brasileiro, divorciado, empresário, nascido em 13/06/1978, portador da carteira de identidade nº 11734474-7 IFP/RJ, inscrito no CPF sob o nº 078.678.257-97, residente e domiciliado na Rua Desembargador Oscar Tenório, nº 95, apto. 102, Recreio dos Bandeirantes, Rio de Janeiro/RJ, CEP 22975-110, doravante designada simplesmente <strong>CONTRATADA</strong> ou <strong>V3</strong>;</p>
<p>e, de outro lado,</p>
<p>{{contratante_qualificacao}}</p>
<p>Sendo CONTRATADA e CONTRATANTE designadas, em conjunto, “<strong>Partes</strong>” e, isoladamente, “<strong>Parte</strong>”, e sendo este instrumento designado “<strong>MANDATO</strong>”.</p>
<h2>CONSIDERANDOS</h2>
<p>I – a CONTRATANTE tem interesse em obter crédito e recursos para suas atividades ou necessidades;</p>
<p>II – a CONTRATADA é empresa de assessoria e intermediação de crédito que se relaciona com Instituições Financeiras Originadoras do Crédito e tem condições de aproximar a CONTRATANTE desses potenciais fornecedores de recursos, bem como de estruturar e defender a operação perante eles;</p>
<p>III – a CONTRATANTE deseja contratar a CONTRATADA para atuar em seu interesse, como assessora independente, na identificação, estruturação, negociação e intermediação de Operações de Crédito;</p>
<p>IV – a análise de crédito, o levantamento e a conferência documental, a estruturação e a defesa de crédito exigem a mobilização de equipe técnica e comercial e geram custos para a CONTRATADA desde o início dos trabalhos, independentemente do resultado;</p>
<p>as Partes resolvem celebrar o presente MANDATO, que se regerá pelas cláusulas e condições abaixo e, no que couber, pelos arts. 653 e seguintes (mandato) e 722 e seguintes (corretagem) do Código Civil.</p>
<h2>CLÁUSULA 1 – DEFINIÇÕES</h2>
<p>1.1. Sem prejuízo de outras definições constantes deste MANDATO, os termos abaixo, quando iniciados em letra maiúscula, terão os seguintes significados:</p>
<p><strong>“Operação de Crédito” ou “Operação”</strong>: qualquer empréstimo, financiamento, adiantamento, antecipação de recebíveis, consórcio contemplado, crédito com garantia (inclusive imobiliária – home equity), capital de giro, emissão de título de crédito ou valor mobiliário, cessão de créditos ou qualquer outra transação de natureza creditícia ou de captação de recursos celebrada pela <strong>CONTRATANTE</strong> (ou por suas Afiliadas, ou por terceiros em seu benefício) com Instituição Financeira Originadora do Crédito, incluindo renovações, aditamentos, prorrogações e novas tranches;</p>
<p><strong>“Afiliadas”</strong>: as sociedades controladoras, controladas, coligadas ou sob controle comum da CONTRATANTE, bem como seus sócios, administradores e as sociedades por eles controladas;</p>
<p><strong>“Instituições Financeiras Originadoras do Crédito” ou “Instituições”</strong>: bancos, cooperativas de crédito, sociedades de crédito direto (SCD), financeiras, fundos de investimento (inclusive FIDCs), securitizadoras, administradoras de consórcio, gestoras (assets), plataformas de crédito e quaisquer outras entidades que concedam ou estruturem crédito, que mantenham ou venham a manter relacionamento com a CONTRATADA;</p>
<p><strong>“Briefing”</strong>: o formulário de briefing, as entrevistas de crédito e as informações prestadas pela CONTRATANTE que delimitam o crédito pretendido (valor, finalidade, prazo, taxa-alvo e garantias disponíveis);</p>
<p><strong>“Aprovação”</strong>: a comunicação, pela Instituição, por escrito ou por meio eletrônico (e-mail, plataforma, sistema ou aplicativo de mensagens), de que o crédito foi aprovado em favor da CONTRATANTE, ainda que sujeita a condições precedentes usuais de mercado (tais como constituição e registro de garantias, avaliação de bens, apresentação de certidões e assinatura dos instrumentos), cujo teor tenha sido repassado pela CONTRATADA à CONTRATANTE;</p>
<p><strong>“Valor Aprovado”</strong>: o valor do crédito constante da Aprovação; havendo mais de uma Aprovação, o daquela escolhida pela CONTRATANTE ou, na ausência de escolha, o da Aprovação de maior valor;</p>
<p><strong>“Valor da Operação”</strong>: o <strong>valor líquido efetivamente liberado</strong> em cada Operação, à vista ou em parcelas, assim entendido o montante creditado em conta de titularidade da CONTRATANTE ou de suas Afiliadas, ou destinado, por sua ordem, à quitação de dívidas, ao pagamento de fornecedores ou a qualquer outra finalidade definida na estruturação, após as deduções retidas na fonte pela Instituição no ato da liberação (tais como IOF, tarifas, seguros, taxas de abertura de crédito e custos de registro). Não serão deduzidos do Valor da Operação (a) os valores que a Instituição, por ordem da CONTRATANTE ou por exigência da estruturação, pagar diretamente a credores ou fornecedores da CONTRATANTE, os quais integram o valor liberado; nem (b) os valores pagos pela CONTRATANTE a terceiros após a liberação, tais como avaliações, despesas cartorárias, regularizações e honorários de assessores. Não integram o Valor da Operação os juros remuneratórios e demais encargos financeiros que incidirão ao longo do prazo da Operação;</p>
<p><strong>“Data da Concretização”</strong>: a data em que os recursos forem efetivamente disponibilizados à CONTRATANTE ou por sua ordem, ou, em operações de antecipação de recebíveis, a data de formalização do limite; em liberações por tranches, a data de cada liberação;</p>
<p><strong>“Remuneração de Sucesso”</strong>: a remuneração devida à CONTRATADA em razão da concretização da Operação, nos termos da Cláusula 3.</p>
<p>1.2. Em operações estruturadas por meio de consórcio, o Valor da Operação corresponderá ao valor do crédito contemplado e efetivamente disponibilizado, e não à soma das cartas de crédito adquiridas.</p>
<h2>CLÁUSULA 2 – DO OBJETO E DA NATUREZA DOS SERVIÇOS</h2>
<p>2.1. A CONTRATANTE contrata a CONTRATADA para identificar, apresentar e intermediar relações comerciais com Instituições Financeiras Originadoras do Crédito, bem como para analisar, estruturar, negociar e defender Operações de Crédito em favor da CONTRATANTE, mediante a remuneração prevista na Cláusula 3.</p>
<p>2.2. Para tanto, a CONTRATADA prestará os serviços com ética, diligência e transparência, competindo-lhe, conforme a necessidade de cada Operação:</p>
<p>a) analisar os dados e documentos necessários à melhor estruturação da Operação, com base no Briefing;</p>
<p>b) estudar o perfil da CONTRATANTE para compreender suas necessidades e requisitos;</p>
<p>c) identificar e apresentar à CONTRATANTE as alternativas de crédito disponíveis no mercado mais adequadas ao seu perfil;</p>
<p>d) analisar as ofertas preliminares e finais apresentadas pelas Instituições;</p>
<p>e) definir a estratégia de negociação e de recebimento de ofertas;</p>
<p>f) apoiar a CONTRATANTE na organização e obtenção de documentos e certidões e nos procedimentos de elegibilidade;</p>
<p>g) estruturar e apresentar a Defesa de Crédito da CONTRATANTE perante as Instituições, inclusive com materiais complementares elaborados em conjunto com a CONTRATANTE;</p>
<p>h) representar a CONTRATANTE perante as Instituições nos processos de due diligence;</p>
<p>i) definir, com os profissionais indicados pela CONTRATANTE, a estrutura da Operação e, quando solicitado, interagir com seus assessores jurídicos na revisão dos instrumentos;</p>
<p>j) coordenar visitas, reuniões e o cronograma da Operação; e</p>
<p>k) conduzir as negociações finais com as Instituições, buscando os melhores termos possíveis para a CONTRATANTE.</p>
<p>2.3. <strong>Poderes.</strong> Para a execução do objeto, a CONTRATANTE outorga à CONTRATADA poderes para representá-la perante as Instituições, com a finalidade de apresentar seu cadastro e documentos, solicitar análises e propostas, receber comunicações e negociar condições comerciais. Não estão compreendidos neste MANDATO poderes para assinar instrumentos de crédito, constituir garantias, receber ou dar quitação de recursos em nome da CONTRATANTE, atos que dependem sempre de manifestação direta da própria CONTRATANTE.</p>
<p>2.4. <strong>Obrigação de meio.</strong> As obrigações da CONTRATADA são de meio e não de resultado. A concessão do crédito, as taxas, prazos, garantias e demais condições são decididos exclusivamente pelas Instituições, segundo suas políticas internas, não havendo garantia de aprovação, de valor ou de condições.</p>
<p>2.5. <strong>Independência.</strong> A CONTRATADA atua, no âmbito deste MANDATO, como assessora contratada pela CONTRATANTE e no interesse desta. A CONTRATADA não é instituição financeira, não capta recursos do público, não concede crédito e não recebe, em nenhuma hipótese, os recursos da Operação em nome da CONTRATANTE.</p>
<h2>CLÁUSULA 3 – DA REMUNERAÇÃO</h2>
<p>3.1. Como contraprestação pelos serviços, a CONTRATANTE pagará à CONTRATADA Remuneração de Sucesso equivalente a <strong>{{percentual_mandato}} do Valor da Operação</strong>, em moeda corrente nacional.</p>
<p>3.2. A Remuneração de Sucesso é devida sobre cada Operação (inclusive renovações, aditamentos, prorrogações, recompras de garantia e novas Operações) celebrada com Instituição apresentada pela CONTRATADA ou em cuja negociação a CONTRATADA tenha atuado. Considera-se que a CONTRATADA atuou na negociação quando prestou, ou esteve disponível para prestar, os serviços da Cláusula 2.</p>
<p>3.3. <strong>Prazo e forma de pagamento.</strong> A Remuneração de Sucesso será paga em até 2 (dois) dias úteis contados da Data da Concretização, por PIX ou transferência para a conta de titularidade da CONTRATADA – PIX CNPJ 14.219.287/0001-50, Banco 403 – Cora SCD, agência 0001, conta 7175979-1 –, servindo o comprovante como recibo. A CONTRATADA emitirá a nota fiscal correspondente em até 1 (um) dia útil após ser informada da concretização.</p>
<p>3.4. <strong>Dever de informar.</strong> A CONTRATANTE informará à CONTRATADA, em até 1 (um) dia útil, a liberação de quaisquer recursos e a assinatura de quaisquer instrumentos relativos à Operação, apresentando, quando solicitado, cópia do contrato e do comprovante de liberação.</p>
<p>3.5. <strong>Pagamento direto pela Instituição.</strong> A CONTRATANTE autoriza, em caráter irrevogável e irretratável, que a Instituição, quando operacionalmente viável, retenha e repasse diretamente à CONTRATADA o valor da Remuneração de Sucesso por ocasião da liberação dos recursos, o que importará quitação da respectiva parcela.</p>
<p>3.6. <strong>Tranches.</strong> Em liberações parceladas, a Remuneração de Sucesso será devida proporcionalmente sobre cada parcela, no prazo da cláusula 3.3 contado de cada liberação. Se a CONTRATANTE, por sua vontade, deixar de utilizar o saldo aprovado e não liberado, aplica-se a esse saldo a Cláusula 4.</p>
<p>3.7. <strong>Antecipação de recebíveis.</strong> Nas operações de antecipação de recebíveis, (a) a Remuneração de Sucesso prevista na cláusula 3.1 incidirá sobre o valor total do limite aprovado e formalizado com a Instituição ou cessionária, independentemente de sua utilização total ou parcial, sendo devida na Data da Concretização; e (b) a CONTRATANTE pagará ainda à CONTRATADA <strong>0,20% (zero vírgula vinte por cento)</strong> sobre cada valor efetivamente antecipado no âmbito desse limite e de suas renovações, em até 2 (dois) dias úteis de cada antecipação.</p>
<p>3.8. <strong>Período de cauda.</strong> A Remuneração de Sucesso será devida, ainda, sobre Operações celebradas com Instituição apresentada pela CONTRATADA em até <strong>24 (vinte e quatro) meses</strong> após o término ou a rescisão deste MANDATO, qualquer que seja o motivo, ainda que a Operação seja celebrada diretamente pela CONTRATANTE, por suas Afiliadas ou por intermédio de terceiros (art. 727 do Código Civil).</p>
<p>3.9. <strong>Tributos.</strong> A remuneração aqui prevista é bruta. Cada Parte responderá pelos tributos de que for contribuinte, observadas as retenções na fonte obrigatórias por lei, que serão destacadas na nota fiscal.</p>
<p>3.10. <strong>Mora.</strong> O atraso em qualquer pagamento sujeitará a Parte inadimplente a multa moratória de 2% (dois por cento), juros de mora de 2% (dois por cento) ao mês, pro rata die, e correção monetária pela variação do IPCA/IBGE, desde o vencimento até o efetivo pagamento, além de honorários advocatícios de 10% (dez por cento) em caso de cobrança extrajudicial por advogado, sem prejuízo dos honorários fixados em juízo. As Partes, ambas pessoas jurídicas, declaram ciência de que a esta obrigação não se aplica o Decreto nº 22.626/1933 (art. 3º da Lei nº 14.905/2024).</p>
<p>3.11. O débito vencido e não pago por mais de 30 (trinta) dias poderá ser levado a protesto e inscrito em cadastros de proteção ao crédito, observadas as comunicações prévias exigidas em lei.</p>
<p>3.12. <strong>Revisão.</strong> Se, antes da Aprovação, ocorrerem alterações relevantes de mercado que tornem inadequada a remuneração pactuada, as Partes poderão negociar de boa-fé novos termos, por escrito. Em nenhuma hipótese haverá redução da remuneração de Operação já aprovada ou concretizada. Não havendo acordo, qualquer Parte poderá resilir este MANDATO nos termos da Cláusula 11, preservados os direitos previstos nas Cláusulas 3 e 4.</p>
<h2>CLÁUSULA 4 – DA DESISTÊNCIA APÓS A APROVAÇÃO (MULTA DE 1%)</h2>
<p>4.1. <strong>Considerando que, até a Aprovação, a CONTRATADA terá mobilizado equipe técnica e comercial, realizado a análise de crédito, o levantamento e a conferência da documentação, a estruturação da Operação, a elaboração da Defesa de Crédito e a interlocução com as Instituições, as Partes ajustam que, ocorrida a Aprovação, a desistência da CONTRATANTE a obrigará a pagar à CONTRATADA multa compensatória equivalente a 1% (um por cento) do Valor Aprovado (“Multa por Desistência”), a título de remuneração pelo trabalho de análise, documentação e equipe efetivamente prestado.</strong></p>
<p>4.2. Considera-se desistência, para os fins desta Cláusula, a ocorrência de qualquer das seguintes hipóteses após a Aprovação:</p>
<p>a) comunicação da CONTRATANTE, por qualquer meio, de que não pretende prosseguir com a Operação, inclusive mediante resilição deste MANDATO;</p>
<p>b) recusa ou omissão, sem justa causa, em assinar os instrumentos da Operação no prazo de 10 (dez) dias úteis contados do seu recebimento;</p>
<p>c) não apresentação de documentos, garantias ou certidões, ou descumprimento de condições precedentes de responsabilidade da CONTRATANTE, no prazo concedido pela Instituição, dando causa à caducidade ou ao cancelamento da Aprovação;</p>
<p>d) ausência de resposta às comunicações da CONTRATADA por mais de 15 (quinze) dias corridos, após notificação específica com menção expressa a esta Cláusula; ou</p>
<p>e) contratação, em substituição à Operação aprovada, de operação de mesma finalidade com instituição não apresentada pela CONTRATADA.</p>
<p>4.3. A Multa por Desistência tem natureza de cláusula penal compensatória, prefixa as perdas e danos decorrentes dos custos de estruturação já incorridos e é exigível independentemente de prova de prejuízo (arts. 408, 409 e 416 do Código Civil), reconhecendo as Partes, desde já, sua proporcionalidade ao trabalho executado (art. 413 do Código Civil). Caso o prejuízo comprovado da CONTRATADA seja superior, esta poderá exigir indenização suplementar, valendo a multa como mínimo (art. 416, parágrafo único, do Código Civil).</p>
<p>4.4. A Multa por Desistência será paga em até 10 (dez) dias corridos contados da notificação da CONTRATADA, na forma da cláusula 3.3, sujeitando-se o atraso à cláusula 3.10.</p>
<p>4.5. A Multa por Desistência não se cumula com a Taxa Administrativa da cláusula 6.4; tendo esta sido paga, seu valor será abatido daquela.</p>
<p>4.6. Se, após a desistência, a Operação, ou outra de mesma finalidade, vier a ser celebrada com Instituição apresentada pela CONTRATADA no prazo da cláusula 3.8, será devida a Remuneração de Sucesso integral, abatido o valor já pago a título de Multa por Desistência.</p>
<p>4.7. <strong>A CONTRATANTE declara ter lido e compreendido esta Cláusula 4, redigida em destaque para permitir sua imediata e fácil compreensão, e que com ela concorda expressamente.</strong></p>
<h2>CLÁUSULA 5 – DA NÃO EXCLUSIVIDADE E DA NÃO CIRCUNVENÇÃO</h2>
<p>5.1. Este MANDATO não é exclusivo. A CONTRATANTE poderá buscar crédito diretamente ou por meio de terceiros, sem que isso gere remuneração à CONTRATADA, <strong>desde que</strong> a Operação não seja celebrada com Instituição apresentada pela CONTRATADA, ressalvado o disposto na Cláusula 4.</p>
<p>5.2. A CONTRATANTE obriga-se a não contornar a CONTRATADA, direta ou indiretamente, inclusive por meio de Afiliadas ou de outros intermediários, para celebrar Operação com Instituição apresentada pela CONTRATADA, sob pena de pagamento da Remuneração de Sucesso integral, como se a Operação tivesse sido intermediada pela CONTRATADA.</p>
<p>5.3. Considera-se apresentada pela CONTRATADA a Instituição à qual o cadastro, a proposta ou a Defesa de Crédito da CONTRATANTE tenha sido submetido pela CONTRATADA, ou cuja identidade a CONTRATADA tenha revelado à CONTRATANTE no curso deste MANDATO, o que poderá ser comprovado por qualquer meio, inclusive e-mails e mensagens eletrônicas.</p>
<h2>CLÁUSULA 6 – DAS OBRIGAÇÕES DAS PARTES</h2>
<p>6.1. As Partes prestarão contas uma à outra sempre que solicitado, com transparência sobre os atos relacionados a este MANDATO.</p>
<p>6.2. A CONTRATADA informará a CONTRATANTE sobre os procedimentos adotados e sobre fatos que possam afetar a prestação dos serviços.</p>
<p>6.3. A CONTRATANTE fornecerá à CONTRATADA, de forma clara, correta, completa e tempestiva, as informações e documentos necessários, respondendo por sua veracidade, exatidão e atualização, e encaminhará toda a documentação constante do checklist disponibilizado pela CONTRATADA no prazo de <strong>30 (trinta) dias corridos</strong> contados da assinatura deste MANDATO.</p>
<p>6.4. <strong>Taxa Administrativa.</strong> O não envio da documentação completa no prazo da cláusula 6.3, sem justificativa aceita por escrito pela CONTRATADA, sujeitará a CONTRATANTE ao pagamento de taxa administrativa equivalente a 1% (um por cento) do valor do crédito solicitado no Briefing, destinada à compensação dos custos administrativos e operacionais já incorridos, a ser paga em até 10 (dez) dias corridos contados do término daquele prazo ou da comunicação formal do descumprimento, o que ocorrer por último.</p>
<p>6.5. A CONTRATADA não responde pela negativa de crédito, pelas condições impostas pelas Instituições ou por inconsistências na documentação apresentada pela CONTRATANTE.</p>
<p>6.6. A Parte que utilizar informações ou documentos falsos, adulterados ou manipulados responderá por todas as perdas, danos, custos e despesas (inclusive honorários advocatícios) daí decorrentes, isentando a outra Parte de qualquer responsabilidade, sem prejuízo da rescisão imediata deste MANDATO.</p>
<p>6.7. Nenhuma das Partes responde por atos praticados pela outra, ou por seus prepostos, em desacordo com este MANDATO.</p>
<h2>CLÁUSULA 7 – DA PROTEÇÃO DE DADOS PESSOAIS</h2>
<p>7.1. As Partes tratarão dados pessoais em conformidade com a Lei nº 13.709/2018 (LGPD), atuando cada uma como controladora independente dos dados que tratar para suas próprias finalidades.</p>
<p>7.2. Os dados pessoais dos sócios, administradores, representantes, garantidores e respectivos cônjuges da CONTRATANTE serão tratados para a execução deste MANDATO e de procedimentos preliminares a ele relacionados (art. 7º, V, LGPD), para a proteção do crédito (art. 7º, X), para o cumprimento de obrigações legais e regulatórias (art. 7º, II) e para o exercício regular de direitos (art. 7º, VI).</p>
<p>7.3. A CONTRATANTE autoriza a CONTRATADA a compartilhar seus dados e documentos com as Instituições, com prestadores de serviço necessários à Operação (avaliadores, cartórios, assessores) e com os parceiros previstos na cláusula 13.1, exclusivamente para as finalidades deste MANDATO, e autoriza a CONTRATADA e as Instituições a consultar o Sistema de Informações de Crédito do Banco Central (SCR) e bases de birôs de crédito a seu respeito e a respeito de seus sócios, administradores e garantidores, que firmam ou anuem a este instrumento cientes desta autorização.</p>
<p>7.4. A CONTRATANTE declara ter informado aos titulares cujos dados fornecer (sócios, administradores, garantidores, cônjuges e demais pessoas) sobre o tratamento e o compartilhamento previstos nesta Cláusula.</p>
<p>7.5. A CONTRATADA adotará medidas técnicas e administrativas aptas a proteger os dados pessoais contra acessos não autorizados e situações ilícitas, comunicará à CONTRATANTE incidentes de segurança que possam acarretar risco ou dano relevante aos titulares e cooperará no atendimento a solicitações de titulares.</p>
<p>7.6. Encerrado o MANDATO, os dados serão eliminados, ressalvada a conservação necessária ao cumprimento de obrigação legal ou regulatória (inclusive de prevenção à lavagem de dinheiro) e ao exercício regular de direitos (art. 16, LGPD).</p>
<h2>CLÁUSULA 8 – DA CONFIDENCIALIDADE</h2>
<p>8.1. Serão consideradas Informações Confidenciais todas as informações, dados, documentos e materiais, de qualquer natureza e em qualquer meio, revelados por uma Parte à outra em razão deste MANDATO, inclusive os termos deste instrumento, as propostas e condições obtidas junto às Instituições, a identidade dos contatos da CONTRATADA nas Instituições e os materiais de Defesa de Crédito.</p>
<p>8.2. Não são confidenciais as informações que (a) sejam ou se tornem de domínio público sem culpa da Parte receptora; (b) já estivessem licitamente em poder da Parte receptora; ou (c) sejam recebidas de terceiros sem dever de sigilo.</p>
<p>8.3. A CONTRATADA poderá compartilhar Informações Confidenciais da CONTRATANTE com as Instituições, com os parceiros e prestadores de serviço referidos na cláusula 7.3 e com seus sócios, empregados e colaboradores, na medida necessária à execução deste MANDATO, desde que sujeitos a dever de sigilo equivalente.</p>
<p>8.4. A CONTRATANTE não poderá divulgar a terceiros, nem utilizar para fins diversos deste MANDATO, as propostas, condições, contatos e materiais fornecidos pela CONTRATADA.</p>
<p>8.5. A Parte obrigada por lei, ordem judicial ou autoridade competente a revelar Informação Confidencial comunicará o fato à outra Parte, quando legalmente permitido, e revelará apenas o estritamente necessário. Não configura violação de sigilo a comunicação feita pela CONTRATADA às autoridades competentes em cumprimento à legislação de prevenção à lavagem de dinheiro.</p>
<p>8.6. As obrigações desta Cláusula vigorarão durante o MANDATO e por 5 (cinco) anos após seu término.</p>
<h2>CLÁUSULA 9 – ANTICORRUPÇÃO E PREVENÇÃO À LAVAGEM DE DINHEIRO</h2>
<p>9.1. As Partes cumprirão a Lei nº 12.846/2013 (Lei Anticorrupção), a Lei nº 9.613/1998 (Lei de Lavagem de Dinheiro) e demais normas aplicáveis, abstendo-se de oferecer, prometer ou pagar, direta ou indiretamente, vantagem indevida a agente público ou privado, inclusive a empregados das Instituições.</p>
<p>9.2. A CONTRATANTE fornecerá as informações cadastrais e de conheça-seu-cliente solicitadas pela CONTRATADA ou pelas Instituições, inclusive quanto à origem de recursos, à composição societária e ao beneficiário final e à condição de pessoa exposta politicamente.</p>
<p>9.3. As Partes declaram que não se encontram sob investigação, processo ou condenação por corrupção, lavagem de dinheiro ou financiamento ao terrorismo, nem sujeitas a sanções ou listas restritivas nacionais ou internacionais.</p>
<p>9.4. A violação desta Cláusula autoriza a rescisão imediata do MANDATO, respondendo a Parte infratora pelas perdas e danos causados.</p>
<h2>CLÁUSULA 10 – DAS DECLARAÇÕES DAS PARTES</h2>
<p>10.1. As Partes declaram que seus signatários estão devidamente autorizados a celebrar este MANDATO, que este constitui obrigação válida, eficaz e exequível e que sua celebração não viola contrato, decisão judicial ou administrativa a que estejam sujeitas.</p>
<p>10.2. A CONTRATADA declara possuir capacidade técnica e estrutura para prestar os serviços conforme as boas práticas de mercado.</p>
<p>10.3. A CONTRATANTE declara que as informações do Briefing são verdadeiras, que não se encontra em recuperação judicial ou extrajudicial ou em processo de falência e que não omitiu fato relevante para a análise de crédito.</p>
<h2>CLÁUSULA 11 – DA VIGÊNCIA E DA RESCISÃO</h2>
<p>11.1. Este MANDATO vigora por prazo indeterminado a partir de sua assinatura e poderá ser resilido por qualquer Parte, sem justa causa, mediante notificação escrita com antecedência mínima de 30 (trinta) dias.</p>
<p>11.2. O MANDATO poderá ser rescindido de imediato, mediante notificação, em caso de (a) descumprimento contratual não sanado em 15 (quinze) dias contados da notificação; (b) falência, recuperação judicial ou extrajudicial ou insolvência da outra Parte; (c) uso de informações ou documentos falsos; ou (d) violação da Cláusula 9.</p>
<p>11.3. A resilição ou rescisão não prejudica (a) a Remuneração de Sucesso das Operações concretizadas ou em curso, nem o período de cauda da cláusula 3.8; (b) a Multa por Desistência, se a resilição pela CONTRATANTE ocorrer após a Aprovação ou se a rescisão decorrer de culpa da CONTRATANTE após a Aprovação; e (c) as obrigações das Cláusulas 7, 8 e 9, que sobrevivem ao término do MANDATO.</p>
<p>11.4. A Parte que der causa à rescisão indenizará a outra pelas perdas e danos comprovados, inclusive honorários advocatícios, observada a Cláusula 12.</p>
<h2>CLÁUSULA 12 – DA RESPONSABILIDADE</h2>
<p>12.1. A responsabilidade total da CONTRATADA por quaisquer danos decorrentes deste MANDATO fica limitada ao valor da remuneração efetivamente recebida na Operação a que se referir o dano, ressalvados os casos de dolo ou culpa grave.</p>
<p>12.2. Nenhuma Parte responderá por lucros cessantes, perda de oportunidade ou danos indiretos, ressalvados os casos de dolo, e a CONTRATADA não responderá por atos de Instituições ou de terceiros que não estejam sob sua subordinação.</p>
<h2>CLÁUSULA 13 – DAS DISPOSIÇÕES GERAIS</h2>
<p>13.1. A CONTRATADA poderá substabelecer, com reserva de iguais poderes, e contratar ou associar-se a terceiros – inclusive Partners credenciados à rede V3, correspondentes e assessores – para a execução deste MANDATO, independentemente de autorização prévia, permanecendo responsável perante a CONTRATANTE e arcando com a remuneração de tais terceiros.</p>
<p>13.2. As comunicações entre as Partes serão feitas por escrito, para os endereços físicos ou eletrônicos indicados no preâmbulo, sendo válidas as realizadas por e-mail e por aplicativo de mensagens aos números informados pelas Partes. Alterações de endereço deverão ser comunicadas por escrito.</p>
<p>13.3. Este MANDATO constitui o acordo integral entre as Partes sobre seu objeto, substitui entendimentos anteriores e somente poderá ser alterado por aditivo escrito.</p>
<p>13.4. A tolerância ou o não exercício de qualquer direito não importará renúncia, novação ou alteração do pactuado. A renúncia somente valerá se expressa e por escrito, interpretando-se restritivamente.</p>
<p>13.5. A nulidade de qualquer disposição não afetará as demais, que permanecerão válidas.</p>
<p>13.6. Nenhuma Parte poderá ceder este MANDATO sem consentimento escrito da outra, salvo a cessão, pela CONTRATADA, dos créditos dele decorrentes.</p>
<p>13.7. Este MANDATO não gera vínculo societário, empregatício ou de representação comercial entre as Partes ou entre uma Parte e os prepostos da outra.</p>
<p>13.8. Este MANDATO, assinado pelas Partes, constitui título executivo extrajudicial (art. 784, III e § 4º, do Código de Processo Civil), obrigando as Partes e seus sucessores a qualquer título, sendo líquidas e certas as obrigações de pagamento nele previstas, apuradas mediante simples cálculo aritmético sobre o Valor da Operação ou o Valor Aprovado.</p>
<p>13.9. As Partes reconhecem a validade da assinatura eletrônica deste instrumento, por certificado ICP-Brasil, pela plataforma gov.br ou por plataforma de assinatura eletrônica que assegure a autoria e a integridade do documento (art. 10, § 2º, da MP nº 2.200-2/2001 e Lei nº 14.063/2020), dispensada a assinatura de testemunhas nos termos do art. 784, § 4º, do Código de Processo Civil.</p>
<h2>CLÁUSULA 14 – DA LEI APLICÁVEL E DO FORO</h2>
<p>14.1. Este MANDATO é regido pelas leis da República Federativa do Brasil. Fica eleito o foro da Comarca da Capital do Estado do Rio de Janeiro, local da sede da CONTRATADA e de cumprimento das obrigações de pagamento, para dirimir quaisquer controvérsias dele decorrentes, com renúncia a qualquer outro, por mais privilegiado que seja.</p>
<p>E, por estarem justas e contratadas, as Partes assinam este instrumento eletronicamente, para que produza seus efeitos legais.</p>
<p>Rio de Janeiro, {{data_geracao_extenso}}.</p>$mandato$, '[{"key": "contratante_qualificacao", "label": "qualificação da contratante", "source": "auto"}, {"key": "percentual_mandato", "label": "percentual do mandato", "source": "auto"}, {"key": "data_geracao_extenso", "label": "data geracao extenso", "source": "auto"}]'::jsonb, 1, true, 'em_revisao', '[]'::jsonb, 'V3C-MAN', 1, 'manual', true, false, '75c6cac4-8d30-436e-b9a6-d5d494d7470b'
where not exists (select 1 from contract_templates where template_name = 'Mandato de Crédito (Cliente PJ)');
